package Trajecto;

/** \file Calculations.java
    \author Zhuo Zhang
    \brief Provides functions for calculating the outputs
    \note Generated by Drasil v0.1-alpha
*/

import java.util.ArrayList;
import org.apache.commons.math3.ode.FirstOrderIntegrator;
import org.apache.commons.math3.ode.nonstiff.DormandPrince54Integrator;

public class Calculations {
    
    /** \brief Calculates dependent variables (m)
        \param κ charge-to-mass ratio (C/kg)
        \param E_x x-component of the electric field (N/C)
        \param B out-of-plane magnetic flux density (T)
        \param E_y y-component of the electric field (N/C)
        \param x_0 initial x-position (m)
        \param y_0 initial y-position (m)
        \param v_x0 initial x-velocity (m/s)
        \param v_y0 initial y-velocity (m/s)
        \param t_final final simulation time (s)
        \return dependent variables (m)
    */
    public static ArrayList<ArrayList<Double>> func_s(double κ, double E_x, double B, double E_y, double x_0, double y_0, double v_x0, double v_y0, double t_final) {
        ArrayList<ArrayList<Double>> s;
        ODEStepHandler stepHandler = new ODEStepHandler();
        ODE ode = new ODE(κ, E_x, E_y, B);
        double[] curr_vals = {x_0, y_0, v_x0, v_y0};
        
        FirstOrderIntegrator it = new DormandPrince54Integrator(1.0e-9, 1.0e-9, 1.0e-6, 1.0e-6);
        it.addStepHandler(stepHandler);
        it.integrate(ode, 0.0, curr_vals, t_final, curr_vals);
        s = stepHandler.s;
        
        return s;
    }
}
