package Trajecto;

/** \file Constants.java
    \author Zhuo Zhang
    \brief Provides the structure for holding constant values
    \note Generated by Drasil v0.1-alpha
*/

/** \brief Structure for holding the constant values
*/
public class Constants {
    public static final double m_min = 1.0e-31;
    public static final double m_max = 1.0e-25;
    public static final double q_max = 1.0e-15;
    public static final double v_max = 1.0e7;
    public static final double E_max = 1000000.0;
    public static final double B_max = 10.0;
    public static final double t_max = 1.0e-4;
    
}
