package Trajecto;

/** \file Control.java
    \author Zhuo Zhang
    \brief Controls the flow of the program
    \note Generated by Drasil v0.1-alpha
*/

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;

public class Control {
    
    /** \brief Controls the flow of the program
        \param args List of command-line arguments
    */
    public static void main(String[] args) throws FileNotFoundException, IOException {
        String filename = args[0];
        double m;
        double q;
        double x_0;
        double y_0;
        double v_x0;
        double v_y0;
        double E_x;
        double E_y;
        double B;
        double t_final;
        double κ;
        double s_0;
        double E_vect;
        double B_vect;
        Object[] outputs = InputParameters.get_input(filename);
        m = (double)(outputs[0]);
        q = (double)(outputs[1]);
        x_0 = (double)(outputs[2]);
        y_0 = (double)(outputs[3]);
        v_x0 = (double)(outputs[4]);
        v_y0 = (double)(outputs[5]);
        E_x = (double)(outputs[6]);
        E_y = (double)(outputs[7]);
        B = (double)(outputs[8]);
        t_final = (double)(outputs[9]);
        outputs = InputParameters.derived_values(q, m, x_0, y_0, v_x0, v_y0, E_x, E_y, B);
        κ = (double)(outputs[0]);
        s_0 = (double)(outputs[1]);
        E_vect = (double)(outputs[2]);
        B_vect = (double)(outputs[3]);
        InputParameters.input_constraints(m, q, x_0, y_0, v_x0, v_y0, E_x, E_y, B, t_final);
        double t_hit = Calculations.func_t_hit(t_final);
        double E_vect_i = Calculations.func_E_vect_i(E_vect);
        ArrayList<ArrayList<Double>> s = Calculations.func_s(κ, E_x, B, E_y, x_0, y_0, v_x0, v_y0, t_final);
        OutputFormat.write_output(s);
    }
}
