package Trajecto;

/** \file Control.java
    \author Zhuo Zhang
    \brief Controls the flow of the program
    \note Generated by Drasil v0.1-alpha
*/

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;

public class Control {
    
    /** \brief Controls the flow of the program
        \param args List of command-line arguments
    */
    public static void main(String[] args) throws FileNotFoundException, IOException {
        String filename = args[0];
        double m;
        double q;
        double x_0;
        double y_0;
        double v_x0;
        double v_y0;
        double N;
        double w;
        double h;
        double x_grid;
        double y_grid;
        double E_x;
        double E_y;
        double B;
        double d_orient;
        double x_det;
        double y_det;
        double y_min^det;
        double y_max^det;
        double x_min^det;
        double x_max^det;
        double t_final;
        double κ;
        double s_0;
        double E_vect;
        double B_vect;
        double R_i;
        double E_vect_i;
        double L_det;
        Object[] outputs = InputParameters.get_input(filename);
        m = (double)(outputs[0]);
        q = (double)(outputs[1]);
        x_0 = (double)(outputs[2]);
        y_0 = (double)(outputs[3]);
        v_x0 = (double)(outputs[4]);
        v_y0 = (double)(outputs[5]);
        N = (double)(outputs[6]);
        w = (double)(outputs[7]);
        h = (double)(outputs[8]);
        x_grid = (double)(outputs[9]);
        y_grid = (double)(outputs[10]);
        E_x = (double)(outputs[11]);
        E_y = (double)(outputs[12]);
        B = (double)(outputs[13]);
        d_orient = (double)(outputs[14]);
        x_det = (double)(outputs[15]);
        y_det = (double)(outputs[16]);
        y_min^det = (double)(outputs[17]);
        y_max^det = (double)(outputs[18]);
        x_min^det = (double)(outputs[19]);
        x_max^det = (double)(outputs[20]);
        t_final = (double)(outputs[21]);
        outputs = InputParameters.derived_values(q, m, x_0, y_0, v_x0, v_y0, E_x, E_y, B, x_grid, y_grid, w, h, d_orient, x_det, y_det, y_min^det, y_max^det, x_min^det, x_max^det);
        κ = (double)(outputs[0]);
        s_0 = (double)(outputs[1]);
        E_vect = (double)(outputs[2]);
        B_vect = (double)(outputs[3]);
        R_i = (double)(outputs[4]);
        E_vect_i = (double)(outputs[5]);
        L_det = (double)(outputs[6]);
        InputParameters.input_constraints(m, q, x_0, y_0, v_x0, v_y0, N, w, h, x_grid, y_grid, E_x, E_y, B, d_orient, x_det, y_det, y_min^det, y_max^det, x_min^det, x_max^det, t_final);
        ArrayList<ArrayList<Double>> s = Calculations.func_s(κ, E_x, B, E_y, x_0, y_0, v_x0, v_y0, t_final);
        OutputFormat.write_output(s);
    }
}
