package Trajecto;

/** \file Control.java
    \author Zhuo Zhang
    \brief Controls the flow of the program
    \note Generated by Drasil v0.1-alpha
*/

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;

public class Control {
    
    /** \brief Controls the flow of the program
        \param args List of command-line arguments
    */
    public static void main(String[] args) throws FileNotFoundException, IOException {
        String filename = args[0];
        double m;
        double q;
        double x_0;
        double y_0;
        double v_x0;
        double v_y0;
        double N;
        double N_col;
        double w;
        double h;
        double x_grid;
        double y_grid;
        double E_x0;
        double E_x1;
        double E_x2;
        double E_x3;
        double E_x4;
        double E_x5;
        double E_y0;
        double E_y1;
        double E_y2;
        double E_y3;
        double E_y4;
        double E_y5;
        double B_0;
        double B_1;
        double B_2;
        double B_3;
        double B_4;
        double B_5;
        double d_orient;
        double x_det;
        double y_det;
        double y_detMin;
        double y_detMax;
        double x_detMin;
        double x_detMax;
        double t_final;
        double κ;
        double s_0;
        double E_vect;
        double B_vect;
        double R_i;
        double E_vect_i;
        double L_det;
        Object[] outputs = InputParameters.get_input(filename);
        m = (double)(outputs[0]);
        q = (double)(outputs[1]);
        x_0 = (double)(outputs[2]);
        y_0 = (double)(outputs[3]);
        v_x0 = (double)(outputs[4]);
        v_y0 = (double)(outputs[5]);
        N = (double)(outputs[6]);
        N_col = (double)(outputs[7]);
        w = (double)(outputs[8]);
        h = (double)(outputs[9]);
        x_grid = (double)(outputs[10]);
        y_grid = (double)(outputs[11]);
        E_x0 = (double)(outputs[12]);
        E_x1 = (double)(outputs[13]);
        E_x2 = (double)(outputs[14]);
        E_x3 = (double)(outputs[15]);
        E_x4 = (double)(outputs[16]);
        E_x5 = (double)(outputs[17]);
        E_y0 = (double)(outputs[18]);
        E_y1 = (double)(outputs[19]);
        E_y2 = (double)(outputs[20]);
        E_y3 = (double)(outputs[21]);
        E_y4 = (double)(outputs[22]);
        E_y5 = (double)(outputs[23]);
        B_0 = (double)(outputs[24]);
        B_1 = (double)(outputs[25]);
        B_2 = (double)(outputs[26]);
        B_3 = (double)(outputs[27]);
        B_4 = (double)(outputs[28]);
        B_5 = (double)(outputs[29]);
        d_orient = (double)(outputs[30]);
        x_det = (double)(outputs[31]);
        y_det = (double)(outputs[32]);
        y_detMin = (double)(outputs[33]);
        y_detMax = (double)(outputs[34]);
        x_detMin = (double)(outputs[35]);
        x_detMax = (double)(outputs[36]);
        t_final = (double)(outputs[37]);
        outputs = InputParameters.derived_values(q, m, x_0, y_0, v_x0, v_y0, E_x0, E_y0, B_0, x_grid, y_grid, w, h, d_orient, x_det, y_det, y_detMin, y_detMax, x_detMin, x_detMax);
        κ = (double)(outputs[0]);
        s_0 = (double)(outputs[1]);
        E_vect = (double)(outputs[2]);
        B_vect = (double)(outputs[3]);
        R_i = (double)(outputs[4]);
        E_vect_i = (double)(outputs[5]);
        L_det = (double)(outputs[6]);
        InputParameters.input_constraints(m, q, x_0, y_0, v_x0, v_y0, N, N_col, w, h, x_grid, y_grid, d_orient, x_det, y_det, y_detMin, y_detMax, x_detMin, x_detMax, t_final);
        ArrayList<ArrayList<Double>> s = Calculations.func_s(κ, E_x0, E_x1, E_x2, E_x3, E_x4, E_x5, x_grid, w, y_grid, h, B_0, B_1, B_2, B_3, B_4, B_5, E_y0, E_y1, E_y2, E_y3, E_y4, E_y5, x_0, y_0, v_x0, v_y0, t_final);
        OutputFormat.write_output(s);
    }
}
