package Trajecto;

/** \file InputParameters.java
    \author Zhuo Zhang
    \brief Provides the function for reading inputs, the function for calculating derived values, and the function for checking the physical constraints and software constraints on the input
    \note Generated by Drasil v0.1-alpha
*/

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

public class InputParameters {
    
    /** \brief Reads input from a file with the given file name
        \param filename name of the input file
        \return array containing the following values:
        \return particle mass (kg)
        \return particle charge (C)
        \return initial x-position (m)
        \return initial y-position (m)
        \return initial x-velocity (m/s)
        \return initial y-velocity (m/s)
        \return number of field regions
        \return number of grid columns
        \return region width (m)
        \return region height (m)
        \return grid origin x-coordinate (m)
        \return grid origin y-coordinate (m)
        \return x-electric field in region 0 (N/C)
        \return x-electric field in region 1 (N/C)
        \return x-electric field in region 2 (N/C)
        \return x-electric field in region 3 (N/C)
        \return x-electric field in region 4 (N/C)
        \return x-electric field in region 5 (N/C)
        \return y-electric field in region 0 (N/C)
        \return y-electric field in region 1 (N/C)
        \return y-electric field in region 2 (N/C)
        \return y-electric field in region 3 (N/C)
        \return y-electric field in region 4 (N/C)
        \return y-electric field in region 5 (N/C)
        \return magnetic flux density in region 0 (T)
        \return magnetic flux density in region 1 (T)
        \return magnetic flux density in region 2 (T)
        \return magnetic flux density in region 3 (T)
        \return magnetic flux density in region 4 (T)
        \return magnetic flux density in region 5 (T)
        \return detector orientation
        \return detector line x-position (m)
        \return detector line y-position (m)
        \return minimum y-coordinate of detector (m)
        \return maximum y-coordinate of detector (m)
        \return minimum x-coordinate of detector (m)
        \return maximum x-coordinate of detector (m)
        \return final simulation time (s)
    */
    public static Object[] get_input(String filename) throws FileNotFoundException {
        double m;
        double q;
        double x_0;
        double y_0;
        double v_x0;
        double v_y0;
        double N;
        double N_col;
        double w;
        double h;
        double x_grid;
        double y_grid;
        double E_x0;
        double E_x1;
        double E_x2;
        double E_x3;
        double E_x4;
        double E_x5;
        double E_y0;
        double E_y1;
        double E_y2;
        double E_y3;
        double E_y4;
        double E_y5;
        double B_0;
        double B_1;
        double B_2;
        double B_3;
        double B_4;
        double B_5;
        double d_orient;
        double x_det;
        double y_det;
        double y_detMin;
        double y_detMax;
        double x_detMin;
        double x_detMax;
        double t_final;
        
        Scanner infile;
        infile = new Scanner(new File(filename));
        infile.nextLine();
        m = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        q = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        x_0 = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        y_0 = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        v_x0 = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        v_y0 = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        N = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        N_col = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        w = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        h = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        x_grid = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        y_grid = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        E_x0 = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        E_x1 = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        E_x2 = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        E_x3 = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        E_x4 = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        E_x5 = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        E_y0 = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        E_y1 = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        E_y2 = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        E_y3 = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        E_y4 = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        E_y5 = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        B_0 = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        B_1 = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        B_2 = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        B_3 = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        B_4 = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        B_5 = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        d_orient = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        x_det = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        y_det = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        y_detMin = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        y_detMax = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        x_detMin = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        x_detMax = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        t_final = Double.parseDouble(infile.nextLine());
        infile.close();
        
        Object[] outputs = new Object[38];
        outputs[0] = m;
        outputs[1] = q;
        outputs[2] = x_0;
        outputs[3] = y_0;
        outputs[4] = v_x0;
        outputs[5] = v_y0;
        outputs[6] = N;
        outputs[7] = N_col;
        outputs[8] = w;
        outputs[9] = h;
        outputs[10] = x_grid;
        outputs[11] = y_grid;
        outputs[12] = E_x0;
        outputs[13] = E_x1;
        outputs[14] = E_x2;
        outputs[15] = E_x3;
        outputs[16] = E_x4;
        outputs[17] = E_x5;
        outputs[18] = E_y0;
        outputs[19] = E_y1;
        outputs[20] = E_y2;
        outputs[21] = E_y3;
        outputs[22] = E_y4;
        outputs[23] = E_y5;
        outputs[24] = B_0;
        outputs[25] = B_1;
        outputs[26] = B_2;
        outputs[27] = B_3;
        outputs[28] = B_4;
        outputs[29] = B_5;
        outputs[30] = d_orient;
        outputs[31] = x_det;
        outputs[32] = y_det;
        outputs[33] = y_detMin;
        outputs[34] = y_detMax;
        outputs[35] = x_detMin;
        outputs[36] = x_detMax;
        outputs[37] = t_final;
        return outputs;
    }
    
    /** \brief Calculates values that can be immediately derived from the inputs
        \param q particle charge (C)
        \param m particle mass (kg)
        \param x_0 initial x-position (m)
        \param y_0 initial y-position (m)
        \param v_x0 initial x-velocity (m/s)
        \param v_y0 initial y-velocity (m/s)
        \param E_x0 x-electric field in region 0 (N/C)
        \param E_y0 y-electric field in region 0 (N/C)
        \param B_0 magnetic flux density in region 0 (T)
        \param x_grid grid origin x-coordinate (m)
        \param y_grid grid origin y-coordinate (m)
        \param w region width (m)
        \param h region height (m)
        \param d_orient detector orientation
        \param x_det detector line x-position (m)
        \param y_det detector line y-position (m)
        \param y_detMin minimum y-coordinate of detector (m)
        \param y_detMax maximum y-coordinate of detector (m)
        \param x_detMin minimum x-coordinate of detector (m)
        \param x_detMax maximum x-coordinate of detector (m)
        \return array containing the following values:
        \return charge-to-mass ratio (C/kg)
        \return initial state vector
        \return electric field vector (N/C)
        \return magnetic flux density vector (T)
        \return rectangular field region
        \return electric field in region i (N/C)
        \return detector line
    */
    public static Object[] derived_values(double q, double m, double x_0, double y_0, double v_x0, double v_y0, double E_x0, double E_y0, double B_0, double x_grid, double y_grid, double w, double h, double d_orient, double x_det, double y_det, double y_detMin, double y_detMax, double x_detMin, double x_detMax) {
        double κ;
        double s_0;
        double E_vect;
        double B_vect;
        double R_i;
        double E_vect_i;
        double L_det;
        
        κ = q / m;
        
        s_0 = {x_0, y_0, v_x0, v_y0};
        
        E_vect = {E_x0, E_y0, 0.0};
        
        B_vect = {0.0, 0.0, B_0};
        
        R_i = {x_grid, y_grid, w, h};
        
        E_vect_i = {E_x0, E_y0, B_0};
        
        L_det = {d_orient, x_det, y_det, y_detMin, y_detMax, x_detMin, x_detMax};
        
        Object[] outputs = new Object[7];
        outputs[0] = κ;
        outputs[1] = s_0;
        outputs[2] = E_vect;
        outputs[3] = B_vect;
        outputs[4] = R_i;
        outputs[5] = E_vect_i;
        outputs[6] = L_det;
        return outputs;
    }
    
    /** \brief Verifies that input values satisfy the physical constraints and software constraints
        \param m particle mass (kg)
        \param q particle charge (C)
        \param x_0 initial x-position (m)
        \param y_0 initial y-position (m)
        \param v_x0 initial x-velocity (m/s)
        \param v_y0 initial y-velocity (m/s)
        \param N number of field regions
        \param N_col number of grid columns
        \param w region width (m)
        \param h region height (m)
        \param x_grid grid origin x-coordinate (m)
        \param y_grid grid origin y-coordinate (m)
        \param d_orient detector orientation
        \param x_det detector line x-position (m)
        \param y_det detector line y-position (m)
        \param y_detMin minimum y-coordinate of detector (m)
        \param y_detMax maximum y-coordinate of detector (m)
        \param x_detMin minimum x-coordinate of detector (m)
        \param x_detMax maximum x-coordinate of detector (m)
        \param t_final final simulation time (s)
    */
    public static void input_constraints(double m, double q, double x_0, double y_0, double v_x0, double v_y0, double N, double N_col, double w, double h, double x_grid, double y_grid, double d_orient, double x_det, double y_det, double y_detMin, double y_detMax, double x_detMin, double x_detMax, double t_final) {
        if (!(Constants.m_min <= m && m <= Constants.m_max)) {
            System.out.print("Warning: ");
            System.out.print("m has value ");
            System.out.print(m);
            System.out.print(", but is suggested to be ");
            System.out.print("between ");
            System.out.print(Constants.m_min);
            System.out.print(" (m_min)");
            System.out.print(" and ");
            System.out.print(Constants.m_max);
            System.out.print(" (m_max)");
            System.out.println(".");
        }
        if (!(-Constants.q_max <= q && q <= Constants.q_max)) {
            System.out.print("Warning: ");
            System.out.print("q has value ");
            System.out.print(q);
            System.out.print(", but is suggested to be ");
            System.out.print("between ");
            System.out.print(-Constants.q_max);
            System.out.print(" (-q_max)");
            System.out.print(" and ");
            System.out.print(Constants.q_max);
            System.out.print(" (q_max)");
            System.out.println(".");
        }
        if (!(-Constants.v_max <= v_x0 && v_x0 <= Constants.v_max)) {
            System.out.print("Warning: ");
            System.out.print("v_x0 has value ");
            System.out.print(v_x0);
            System.out.print(", but is suggested to be ");
            System.out.print("between ");
            System.out.print(-Constants.v_max);
            System.out.print(" (-v_max)");
            System.out.print(" and ");
            System.out.print(Constants.v_max);
            System.out.print(" (v_max)");
            System.out.println(".");
        }
        if (!(-Constants.v_max <= v_y0 && v_y0 <= Constants.v_max)) {
            System.out.print("Warning: ");
            System.out.print("v_y0 has value ");
            System.out.print(v_y0);
            System.out.print(", but is suggested to be ");
            System.out.print("between ");
            System.out.print(-Constants.v_max);
            System.out.print(" (-v_max)");
            System.out.print(" and ");
            System.out.print(Constants.v_max);
            System.out.print(" (v_max)");
            System.out.println(".");
        }
        if (!(0.0 <= d_orient && d_orient <= 1.0)) {
            System.out.print("Warning: ");
            System.out.print("d_orient has value ");
            System.out.print(d_orient);
            System.out.print(", but is suggested to be ");
            System.out.print("between ");
            System.out.print(0.0);
            System.out.print(" and ");
            System.out.print(1.0);
            System.out.println(".");
        }
        if (!(t_final <= Constants.t_max)) {
            System.out.print("Warning: ");
            System.out.print("t_final has value ");
            System.out.print(t_final);
            System.out.print(", but is suggested to be ");
            System.out.print("below ");
            System.out.print(Constants.t_max);
            System.out.print(" (t_max)");
            System.out.println(".");
        }
        
        if (!(m > 0.0)) {
            System.out.print("Warning: ");
            System.out.print("m has value ");
            System.out.print(m);
            System.out.print(", but is suggested to be ");
            System.out.print("above ");
            System.out.print(0.0);
            System.out.println(".");
        }
        if (!(N > 0.0)) {
            System.out.print("Warning: ");
            System.out.print("N has value ");
            System.out.print(N);
            System.out.print(", but is suggested to be ");
            System.out.print("above ");
            System.out.print(0.0);
            System.out.println(".");
        }
        if (!(N_col > 0.0)) {
            System.out.print("Warning: ");
            System.out.print("N_col has value ");
            System.out.print(N_col);
            System.out.print(", but is suggested to be ");
            System.out.print("above ");
            System.out.print(0.0);
            System.out.println(".");
        }
        if (!(w > 0.0)) {
            System.out.print("Warning: ");
            System.out.print("w has value ");
            System.out.print(w);
            System.out.print(", but is suggested to be ");
            System.out.print("above ");
            System.out.print(0.0);
            System.out.println(".");
        }
        if (!(h > 0.0)) {
            System.out.print("Warning: ");
            System.out.print("h has value ");
            System.out.print(h);
            System.out.print(", but is suggested to be ");
            System.out.print("above ");
            System.out.print(0.0);
            System.out.println(".");
        }
        if (!(t_final > 0.0)) {
            System.out.print("Warning: ");
            System.out.print("t_final has value ");
            System.out.print(t_final);
            System.out.print(", but is suggested to be ");
            System.out.print("above ");
            System.out.print(0.0);
            System.out.println(".");
        }
    }
}
