package Trajecto;

/** \file InputParameters.java
    \author Zhuo Zhang
    \brief Provides the function for reading inputs, the function for calculating derived values, and the function for checking the physical constraints and software constraints on the input
    \note Generated by Drasil v0.1-alpha
*/

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

public class InputParameters {
    
    /** \brief Reads input from a file with the given file name
        \param filename name of the input file
        \return array containing the following values:
        \return particle mass (kg)
        \return particle charge (C)
        \return initial x-position (m)
        \return initial y-position (m)
        \return initial x-velocity (m/s)
        \return initial y-velocity (m/s)
        \return number of field regions
        \return region width (m)
        \return region height (m)
        \return grid origin x-coordinate (m)
        \return grid origin y-coordinate (m)
        \return x-component of the electric field (N/C)
        \return y-component of the electric field (N/C)
        \return out-of-plane magnetic flux density (T)
        \return detector orientation
        \return detector line x-position (m)
        \return detector line y-position (m)
        \return minimum y-coordinate of detector (m)
        \return maximum y-coordinate of detector (m)
        \return minimum x-coordinate of detector (m)
        \return maximum x-coordinate of detector (m)
        \return final simulation time (s)
    */
    public static Object[] get_input(String filename) throws FileNotFoundException {
        double m;
        double q;
        double x_0;
        double y_0;
        double v_x0;
        double v_y0;
        double N;
        double w;
        double h;
        double x_grid;
        double y_grid;
        double E_x;
        double E_y;
        double B;
        double d_orient;
        double x_det;
        double y_det;
        double y_min^det;
        double y_max^det;
        double x_min^det;
        double x_max^det;
        double t_final;
        
        Scanner infile;
        infile = new Scanner(new File(filename));
        infile.nextLine();
        m = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        q = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        x_0 = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        y_0 = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        v_x0 = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        v_y0 = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        N = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        w = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        h = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        x_grid = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        y_grid = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        E_x = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        E_y = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        B = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        d_orient = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        x_det = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        y_det = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        y_min^det = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        y_max^det = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        x_min^det = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        x_max^det = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        t_final = Double.parseDouble(infile.nextLine());
        infile.close();
        
        Object[] outputs = new Object[22];
        outputs[0] = m;
        outputs[1] = q;
        outputs[2] = x_0;
        outputs[3] = y_0;
        outputs[4] = v_x0;
        outputs[5] = v_y0;
        outputs[6] = N;
        outputs[7] = w;
        outputs[8] = h;
        outputs[9] = x_grid;
        outputs[10] = y_grid;
        outputs[11] = E_x;
        outputs[12] = E_y;
        outputs[13] = B;
        outputs[14] = d_orient;
        outputs[15] = x_det;
        outputs[16] = y_det;
        outputs[17] = y_min^det;
        outputs[18] = y_max^det;
        outputs[19] = x_min^det;
        outputs[20] = x_max^det;
        outputs[21] = t_final;
        return outputs;
    }
    
    /** \brief Calculates values that can be immediately derived from the inputs
        \param q particle charge (C)
        \param m particle mass (kg)
        \param x_0 initial x-position (m)
        \param y_0 initial y-position (m)
        \param v_x0 initial x-velocity (m/s)
        \param v_y0 initial y-velocity (m/s)
        \param E_x x-component of the electric field (N/C)
        \param E_y y-component of the electric field (N/C)
        \param B out-of-plane magnetic flux density (T)
        \param x_grid grid origin x-coordinate (m)
        \param y_grid grid origin y-coordinate (m)
        \param w region width (m)
        \param h region height (m)
        \param d_orient detector orientation
        \param x_det detector line x-position (m)
        \param y_det detector line y-position (m)
        \param y_min^det minimum y-coordinate of detector (m)
        \param y_max^det maximum y-coordinate of detector (m)
        \param x_min^det minimum x-coordinate of detector (m)
        \param x_max^det maximum x-coordinate of detector (m)
        \return array containing the following values:
        \return charge-to-mass ratio (C/kg)
        \return initial state vector
        \return electric field vector (N/C)
        \return magnetic flux density vector (T)
        \return rectangular field region
        \return electric field in region i (N/C)
        \return detector line
    */
    public static Object[] derived_values(double q, double m, double x_0, double y_0, double v_x0, double v_y0, double E_x, double E_y, double B, double x_grid, double y_grid, double w, double h, double d_orient, double x_det, double y_det, double y_min^det, double y_max^det, double x_min^det, double x_max^det) {
        double κ;
        double s_0;
        double E_vect;
        double B_vect;
        double R_i;
        double E_vect_i;
        double L_det;
        
        κ = q / m;
        
        s_0 = {x_0, y_0, v_x0, v_y0};
        
        E_vect = {E_x, E_y, 0.0};
        
        B_vect = {0.0, 0.0, B};
        
        R_i = {x_grid, y_grid, w, h};
        
        E_vect_i = {E_x, E_y, B};
        
        L_det = {d_orient, x_det, y_det, y_min^det, y_max^det, x_min^det, x_max^det};
        
        Object[] outputs = new Object[7];
        outputs[0] = κ;
        outputs[1] = s_0;
        outputs[2] = E_vect;
        outputs[3] = B_vect;
        outputs[4] = R_i;
        outputs[5] = E_vect_i;
        outputs[6] = L_det;
        return outputs;
    }
    
    /** \brief Verifies that input values satisfy the physical constraints and software constraints
        \param m particle mass (kg)
        \param q particle charge (C)
        \param x_0 initial x-position (m)
        \param y_0 initial y-position (m)
        \param v_x0 initial x-velocity (m/s)
        \param v_y0 initial y-velocity (m/s)
        \param N number of field regions
        \param w region width (m)
        \param h region height (m)
        \param x_grid grid origin x-coordinate (m)
        \param y_grid grid origin y-coordinate (m)
        \param E_x x-component of the electric field (N/C)
        \param E_y y-component of the electric field (N/C)
        \param B out-of-plane magnetic flux density (T)
        \param d_orient detector orientation
        \param x_det detector line x-position (m)
        \param y_det detector line y-position (m)
        \param y_min^det minimum y-coordinate of detector (m)
        \param y_max^det maximum y-coordinate of detector (m)
        \param x_min^det minimum x-coordinate of detector (m)
        \param x_max^det maximum x-coordinate of detector (m)
        \param t_final final simulation time (s)
    */
    public static void input_constraints(double m, double q, double x_0, double y_0, double v_x0, double v_y0, double N, double w, double h, double x_grid, double y_grid, double E_x, double E_y, double B, double d_orient, double x_det, double y_det, double y_min^det, double y_max^det, double x_min^det, double x_max^det, double t_final) {
        if (!(Constants.m_min <= m && m <= Constants.m_max)) {
            System.out.print("Warning: ");
            System.out.print("m has value ");
            System.out.print(m);
            System.out.print(", but is suggested to be ");
            System.out.print("between ");
            System.out.print(Constants.m_min);
            System.out.print(" (m_min)");
            System.out.print(" and ");
            System.out.print(Constants.m_max);
            System.out.print(" (m_max)");
            System.out.println(".");
        }
        if (!(-Constants.q_max <= q && q <= Constants.q_max)) {
            System.out.print("Warning: ");
            System.out.print("q has value ");
            System.out.print(q);
            System.out.print(", but is suggested to be ");
            System.out.print("between ");
            System.out.print(-Constants.q_max);
            System.out.print(" (-q_max)");
            System.out.print(" and ");
            System.out.print(Constants.q_max);
            System.out.print(" (q_max)");
            System.out.println(".");
        }
        if (!(-Constants.v_max <= v_x0 && v_x0 <= Constants.v_max)) {
            System.out.print("Warning: ");
            System.out.print("v_x0 has value ");
            System.out.print(v_x0);
            System.out.print(", but is suggested to be ");
            System.out.print("between ");
            System.out.print(-Constants.v_max);
            System.out.print(" (-v_max)");
            System.out.print(" and ");
            System.out.print(Constants.v_max);
            System.out.print(" (v_max)");
            System.out.println(".");
        }
        if (!(-Constants.v_max <= v_y0 && v_y0 <= Constants.v_max)) {
            System.out.print("Warning: ");
            System.out.print("v_y0 has value ");
            System.out.print(v_y0);
            System.out.print(", but is suggested to be ");
            System.out.print("between ");
            System.out.print(-Constants.v_max);
            System.out.print(" (-v_max)");
            System.out.print(" and ");
            System.out.print(Constants.v_max);
            System.out.print(" (v_max)");
            System.out.println(".");
        }
        if (!(-Constants.E_max <= E_x && E_x <= Constants.E_max)) {
            System.out.print("Warning: ");
            System.out.print("E_x has value ");
            System.out.print(E_x);
            System.out.print(", but is suggested to be ");
            System.out.print("between ");
            System.out.print(-Constants.E_max);
            System.out.print(" (-E_max)");
            System.out.print(" and ");
            System.out.print(Constants.E_max);
            System.out.print(" (E_max)");
            System.out.println(".");
        }
        if (!(-Constants.E_max <= E_y && E_y <= Constants.E_max)) {
            System.out.print("Warning: ");
            System.out.print("E_y has value ");
            System.out.print(E_y);
            System.out.print(", but is suggested to be ");
            System.out.print("between ");
            System.out.print(-Constants.E_max);
            System.out.print(" (-E_max)");
            System.out.print(" and ");
            System.out.print(Constants.E_max);
            System.out.print(" (E_max)");
            System.out.println(".");
        }
        if (!(-Constants.B_max <= B && B <= Constants.B_max)) {
            System.out.print("Warning: ");
            System.out.print("B has value ");
            System.out.print(B);
            System.out.print(", but is suggested to be ");
            System.out.print("between ");
            System.out.print(-Constants.B_max);
            System.out.print(" (-B_max)");
            System.out.print(" and ");
            System.out.print(Constants.B_max);
            System.out.print(" (B_max)");
            System.out.println(".");
        }
        if (!(0.0 <= d_orient && d_orient <= 1.0)) {
            System.out.print("Warning: ");
            System.out.print("d_orient has value ");
            System.out.print(d_orient);
            System.out.print(", but is suggested to be ");
            System.out.print("between ");
            System.out.print(0.0);
            System.out.print(" and ");
            System.out.print(1.0);
            System.out.println(".");
        }
        if (!(t_final <= Constants.t_max)) {
            System.out.print("Warning: ");
            System.out.print("t_final has value ");
            System.out.print(t_final);
            System.out.print(", but is suggested to be ");
            System.out.print("below ");
            System.out.print(Constants.t_max);
            System.out.print(" (t_max)");
            System.out.println(".");
        }
        
        if (!(m > 0.0)) {
            System.out.print("Warning: ");
            System.out.print("m has value ");
            System.out.print(m);
            System.out.print(", but is suggested to be ");
            System.out.print("above ");
            System.out.print(0.0);
            System.out.println(".");
        }
        if (!(N > 0.0)) {
            System.out.print("Warning: ");
            System.out.print("N has value ");
            System.out.print(N);
            System.out.print(", but is suggested to be ");
            System.out.print("above ");
            System.out.print(0.0);
            System.out.println(".");
        }
        if (!(w > 0.0)) {
            System.out.print("Warning: ");
            System.out.print("w has value ");
            System.out.print(w);
            System.out.print(", but is suggested to be ");
            System.out.print("above ");
            System.out.print(0.0);
            System.out.println(".");
        }
        if (!(h > 0.0)) {
            System.out.print("Warning: ");
            System.out.print("h has value ");
            System.out.print(h);
            System.out.print(", but is suggested to be ");
            System.out.print("above ");
            System.out.print(0.0);
            System.out.println(".");
        }
        if (!(t_final > 0.0)) {
            System.out.print("Warning: ");
            System.out.print("t_final has value ");
            System.out.print(t_final);
            System.out.print(", but is suggested to be ");
            System.out.print("above ");
            System.out.print(0.0);
            System.out.println(".");
        }
    }
}
