package Trajecto;

/** \file InputParameters.java
    \author Zhuo Zhang
    \brief Provides the function for reading inputs, the function for calculating derived values, and the function for checking the physical constraints and software constraints on the input
    \note Generated by Drasil v0.1-alpha
*/

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

public class InputParameters {
    
    /** \brief Reads input from a file with the given file name
        \param filename name of the input file
        \return array containing the following values:
        \return particle mass (kg)
        \return particle charge (C)
        \return initial x-position (m)
        \return initial y-position (m)
        \return initial x-velocity (m/s)
        \return initial y-velocity (m/s)
        \return x-component of the electric field (N/C)
        \return y-component of the electric field (N/C)
        \return out-of-plane magnetic flux density (T)
        \return final simulation time (s)
    */
    public static Object[] get_input(String filename) throws FileNotFoundException {
        double m;
        double q;
        double x_0;
        double y_0;
        double v_x0;
        double v_y0;
        double E_x;
        double E_y;
        double B;
        double t_final;
        
        Scanner infile;
        infile = new Scanner(new File(filename));
        infile.nextLine();
        m = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        q = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        x_0 = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        y_0 = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        v_x0 = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        v_y0 = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        E_x = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        E_y = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        B = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        t_final = Double.parseDouble(infile.nextLine());
        infile.close();
        
        Object[] outputs = new Object[10];
        outputs[0] = m;
        outputs[1] = q;
        outputs[2] = x_0;
        outputs[3] = y_0;
        outputs[4] = v_x0;
        outputs[5] = v_y0;
        outputs[6] = E_x;
        outputs[7] = E_y;
        outputs[8] = B;
        outputs[9] = t_final;
        return outputs;
    }
    
    /** \brief Calculates values that can be immediately derived from the inputs
        \param q particle charge (C)
        \param m particle mass (kg)
        \param x_0 initial x-position (m)
        \param y_0 initial y-position (m)
        \param v_x0 initial x-velocity (m/s)
        \param v_y0 initial y-velocity (m/s)
        \param E_x x-component of the electric field (N/C)
        \param E_y y-component of the electric field (N/C)
        \param B out-of-plane magnetic flux density (T)
        \return array containing the following values:
        \return charge-to-mass ratio (C/kg)
        \return initial state vector
        \return electric field vector (N/C)
        \return magnetic flux density vector (T)
    */
    public static Object[] derived_values(double q, double m, double x_0, double y_0, double v_x0, double v_y0, double E_x, double E_y, double B) {
        double κ;
        double s_0;
        double E_vect;
        double B_vect;
        
        κ = q / m;
        
        s_0 = {x_0, y_0, v_x0, v_y0};
        
        E_vect = {E_x, E_y, 0.0};
        
        B_vect = {0.0, 0.0, B};
        
        Object[] outputs = new Object[4];
        outputs[0] = κ;
        outputs[1] = s_0;
        outputs[2] = E_vect;
        outputs[3] = B_vect;
        return outputs;
    }
    
    /** \brief Verifies that input values satisfy the physical constraints and software constraints
        \param m particle mass (kg)
        \param q particle charge (C)
        \param x_0 initial x-position (m)
        \param y_0 initial y-position (m)
        \param v_x0 initial x-velocity (m/s)
        \param v_y0 initial y-velocity (m/s)
        \param E_x x-component of the electric field (N/C)
        \param E_y y-component of the electric field (N/C)
        \param B out-of-plane magnetic flux density (T)
        \param t_final final simulation time (s)
    */
    public static void input_constraints(double m, double q, double x_0, double y_0, double v_x0, double v_y0, double E_x, double E_y, double B, double t_final) {
        if (!(Constants.m_min <= m && m <= Constants.m_max)) {
            System.out.print("Warning: ");
            System.out.print("m has value ");
            System.out.print(m);
            System.out.print(", but is suggested to be ");
            System.out.print("between ");
            System.out.print(Constants.m_min);
            System.out.print(" (m_min)");
            System.out.print(" and ");
            System.out.print(Constants.m_max);
            System.out.print(" (m_max)");
            System.out.println(".");
        }
        if (!(-Constants.q_max <= q && q <= Constants.q_max)) {
            System.out.print("Warning: ");
            System.out.print("q has value ");
            System.out.print(q);
            System.out.print(", but is suggested to be ");
            System.out.print("between ");
            System.out.print(-Constants.q_max);
            System.out.print(" (-q_max)");
            System.out.print(" and ");
            System.out.print(Constants.q_max);
            System.out.print(" (q_max)");
            System.out.println(".");
        }
        if (!(-Constants.v_max <= v_x0 && v_x0 <= Constants.v_max)) {
            System.out.print("Warning: ");
            System.out.print("v_x0 has value ");
            System.out.print(v_x0);
            System.out.print(", but is suggested to be ");
            System.out.print("between ");
            System.out.print(-Constants.v_max);
            System.out.print(" (-v_max)");
            System.out.print(" and ");
            System.out.print(Constants.v_max);
            System.out.print(" (v_max)");
            System.out.println(".");
        }
        if (!(-Constants.v_max <= v_y0 && v_y0 <= Constants.v_max)) {
            System.out.print("Warning: ");
            System.out.print("v_y0 has value ");
            System.out.print(v_y0);
            System.out.print(", but is suggested to be ");
            System.out.print("between ");
            System.out.print(-Constants.v_max);
            System.out.print(" (-v_max)");
            System.out.print(" and ");
            System.out.print(Constants.v_max);
            System.out.print(" (v_max)");
            System.out.println(".");
        }
        if (!(-Constants.E_max <= E_x && E_x <= Constants.E_max)) {
            System.out.print("Warning: ");
            System.out.print("E_x has value ");
            System.out.print(E_x);
            System.out.print(", but is suggested to be ");
            System.out.print("between ");
            System.out.print(-Constants.E_max);
            System.out.print(" (-E_max)");
            System.out.print(" and ");
            System.out.print(Constants.E_max);
            System.out.print(" (E_max)");
            System.out.println(".");
        }
        if (!(-Constants.E_max <= E_y && E_y <= Constants.E_max)) {
            System.out.print("Warning: ");
            System.out.print("E_y has value ");
            System.out.print(E_y);
            System.out.print(", but is suggested to be ");
            System.out.print("between ");
            System.out.print(-Constants.E_max);
            System.out.print(" (-E_max)");
            System.out.print(" and ");
            System.out.print(Constants.E_max);
            System.out.print(" (E_max)");
            System.out.println(".");
        }
        if (!(-Constants.B_max <= B && B <= Constants.B_max)) {
            System.out.print("Warning: ");
            System.out.print("B has value ");
            System.out.print(B);
            System.out.print(", but is suggested to be ");
            System.out.print("between ");
            System.out.print(-Constants.B_max);
            System.out.print(" (-B_max)");
            System.out.print(" and ");
            System.out.print(Constants.B_max);
            System.out.print(" (B_max)");
            System.out.println(".");
        }
        if (!(t_final <= Constants.t_max)) {
            System.out.print("Warning: ");
            System.out.print("t_final has value ");
            System.out.print(t_final);
            System.out.print(", but is suggested to be ");
            System.out.print("below ");
            System.out.print(Constants.t_max);
            System.out.print(" (t_max)");
            System.out.println(".");
        }
        
        if (!(m > 0.0)) {
            System.out.print("Warning: ");
            System.out.print("m has value ");
            System.out.print(m);
            System.out.print(", but is suggested to be ");
            System.out.print("above ");
            System.out.print(0.0);
            System.out.println(".");
        }
        if (!(t_final > 0.0)) {
            System.out.print("Warning: ");
            System.out.print("t_final has value ");
            System.out.print(t_final);
            System.out.print(", but is suggested to be ");
            System.out.print("above ");
            System.out.print(0.0);
            System.out.println(".");
        }
    }
}
