package Trajecto;

/** \file ODE.java
    \author Zhuo Zhang
    \brief Class representing an ODE system
    \note Generated by Drasil v0.1-alpha
*/

import org.apache.commons.math3.ode.FirstOrderDifferentialEquations;

/** \brief Class representing an ODE system
*/
public class ODE implements FirstOrderDifferentialEquations {
    private double κ;
    private double E_x;
    private double E_y;
    private double B;
    
    /** \brief Constructor for ODE objects
        \param κ charge-to-mass ratio (C/kg)
        \param E_x x-component of the electric field (N/C)
        \param E_y y-component of the electric field (N/C)
        \param B out-of-plane magnetic flux density (T)
    */
    public ODE(double κ, double E_x, double E_y, double B) {
        this.κ = κ;
        this.E_x = E_x;
        this.E_y = E_y;
        this.B = B;
    }
    
    /** \brief returns the ODE system dimension
        \return dimension of the ODE system
    */
    public int getDimension() {
        return 4;
    }
    
    /** \brief function representation of an ODE system
        \param t current independent variable value in ODE solution
        \param s dependent variables (m)
        \param ds change in dependent variables (m)
    */
    public void computeDerivatives(double t, double[] s, double[] ds) {
        ds[0] = s[2];
        ds[1] = s[3];
        ds[2] = κ * (E_x + s[3] * B);
        ds[3] = κ * (E_y - s[2] * B);
    }
}
