package Trajecto;

/** \file ODE.java
    \author Zhuo Zhang
    \brief Class representing an ODE system
    \note Generated by Drasil v0.1-alpha
*/

import java.util.ArrayList;
import org.apache.commons.math3.ode.FirstOrderDifferentialEquations;

/** \brief Class representing an ODE system
*/
public class ODE implements FirstOrderDifferentialEquations {
    private double κ;
    private double E_x0;
    private double E_x1;
    private double E_x2;
    private double E_x3;
    private double E_x4;
    private double E_x5;
    private double E_y0;
    private double E_y1;
    private double E_y2;
    private double E_y3;
    private double E_y4;
    private double E_y5;
    private double B_0;
    private double B_1;
    private double B_2;
    private double B_3;
    private double B_4;
    private double B_5;
    private double x_grid;
    private double y_grid;
    private double w;
    private double h;
    
    /** \brief Constructor for ODE objects
        \param κ charge-to-mass ratio (C/kg)
        \param E_x0 x-electric field in region 0 (N/C)
        \param E_x1 x-electric field in region 1 (N/C)
        \param E_x2 x-electric field in region 2 (N/C)
        \param E_x3 x-electric field in region 3 (N/C)
        \param E_x4 x-electric field in region 4 (N/C)
        \param E_x5 x-electric field in region 5 (N/C)
        \param E_y0 y-electric field in region 0 (N/C)
        \param E_y1 y-electric field in region 1 (N/C)
        \param E_y2 y-electric field in region 2 (N/C)
        \param E_y3 y-electric field in region 3 (N/C)
        \param E_y4 y-electric field in region 4 (N/C)
        \param E_y5 y-electric field in region 5 (N/C)
        \param B_0 magnetic flux density in region 0 (T)
        \param B_1 magnetic flux density in region 1 (T)
        \param B_2 magnetic flux density in region 2 (T)
        \param B_3 magnetic flux density in region 3 (T)
        \param B_4 magnetic flux density in region 4 (T)
        \param B_5 magnetic flux density in region 5 (T)
        \param x_grid grid origin x-coordinate (m)
        \param y_grid grid origin y-coordinate (m)
        \param w region width (m)
        \param h region height (m)
    */
    public ODE(double κ, double E_x0, double E_x1, double E_x2, double E_x3, double E_x4, double E_x5, double E_y0, double E_y1, double E_y2, double E_y3, double E_y4, double E_y5, double B_0, double B_1, double B_2, double B_3, double B_4, double B_5, double x_grid, double y_grid, double w, double h) {
        this.κ = κ;
        this.E_x0 = E_x0;
        this.E_x1 = E_x1;
        this.E_x2 = E_x2;
        this.E_x3 = E_x3;
        this.E_x4 = E_x4;
        this.E_x5 = E_x5;
        this.E_y0 = E_y0;
        this.E_y1 = E_y1;
        this.E_y2 = E_y2;
        this.E_y3 = E_y3;
        this.E_y4 = E_y4;
        this.E_y5 = E_y5;
        this.B_0 = B_0;
        this.B_1 = B_1;
        this.B_2 = B_2;
        this.B_3 = B_3;
        this.B_4 = B_4;
        this.B_5 = B_5;
        this.x_grid = x_grid;
        this.y_grid = y_grid;
        this.w = w;
        this.h = h;
    }
    
    /** \brief returns the ODE system dimension
        \return dimension of the ODE system
    */
    public int getDimension() {
        return 4;
    }
    
    /** \brief function representation of an ODE system
        \param t current independent variable value in ODE solution
        \param s dependent variables (m)
        \param ds change in dependent variables (m)
    */
    public void computeDerivatives(double t, double[] s, double[] ds) {
        ArrayList<Double> s;
        
        ds[0] = s[2];
        ds[1] = s[3];
        ds[2] = κ * ((s.get(0) >= x_grid + 0.0 * w && (s.get(0) < x_grid + w && (s.get(1) >= y_grid + 0.0 * h && s.get(1) < y_grid + h)) ? E_x0 : s.get(0) >= x_grid + w && (s.get(0) < x_grid + 2.0 * w && (s.get(1) >= y_grid + 0.0 * h && s.get(1) < y_grid + h)) ? E_x1 : s.get(0) >= x_grid + 2.0 * w && (s.get(0) < x_grid + 3.0 * w && (s.get(1) >= y_grid + 0.0 * h && s.get(1) < y_grid + h)) ? E_x2 : s.get(0) >= x_grid + 0.0 * w && (s.get(0) < x_grid + w && (s.get(1) >= y_grid + h && s.get(1) < y_grid + 2.0 * h)) ? E_x3 : s.get(0) >= x_grid + w && (s.get(0) < x_grid + 2.0 * w && (s.get(1) >= y_grid + h && s.get(1) < y_grid + 2.0 * h)) ? E_x4 : s.get(0) >= x_grid + 2.0 * w && (s.get(0) < x_grid + 3.0 * w && (s.get(1) >= y_grid + h && s.get(1) < y_grid + 2.0 * h)) ? E_x5 : 0.0) + s[3] * (s.get(0) >= x_grid + 0.0 * w && (s.get(0) < x_grid + w && (s.get(1) >= y_grid + 0.0 * h && s.get(1) < y_grid + h)) ? B_0 : s.get(0) >= x_grid + w && (s.get(0) < x_grid + 2.0 * w && (s.get(1) >= y_grid + 0.0 * h && s.get(1) < y_grid + h)) ? B_1 : s.get(0) >= x_grid + 2.0 * w && (s.get(0) < x_grid + 3.0 * w && (s.get(1) >= y_grid + 0.0 * h && s.get(1) < y_grid + h)) ? B_2 : s.get(0) >= x_grid + 0.0 * w && (s.get(0) < x_grid + w && (s.get(1) >= y_grid + h && s.get(1) < y_grid + 2.0 * h)) ? B_3 : s.get(0) >= x_grid + w && (s.get(0) < x_grid + 2.0 * w && (s.get(1) >= y_grid + h && s.get(1) < y_grid + 2.0 * h)) ? B_4 : s.get(0) >= x_grid + 2.0 * w && (s.get(0) < x_grid + 3.0 * w && (s.get(1) >= y_grid + h && s.get(1) < y_grid + 2.0 * h)) ? B_5 : 0.0));
        ds[3] = κ * ((s.get(0) >= x_grid + 0.0 * w && (s.get(0) < x_grid + w && (s.get(1) >= y_grid + 0.0 * h && s.get(1) < y_grid + h)) ? E_y0 : s.get(0) >= x_grid + w && (s.get(0) < x_grid + 2.0 * w && (s.get(1) >= y_grid + 0.0 * h && s.get(1) < y_grid + h)) ? E_y1 : s.get(0) >= x_grid + 2.0 * w && (s.get(0) < x_grid + 3.0 * w && (s.get(1) >= y_grid + 0.0 * h && s.get(1) < y_grid + h)) ? E_y2 : s.get(0) >= x_grid + 0.0 * w && (s.get(0) < x_grid + w && (s.get(1) >= y_grid + h && s.get(1) < y_grid + 2.0 * h)) ? E_y3 : s.get(0) >= x_grid + w && (s.get(0) < x_grid + 2.0 * w && (s.get(1) >= y_grid + h && s.get(1) < y_grid + 2.0 * h)) ? E_y4 : s.get(0) >= x_grid + 2.0 * w && (s.get(0) < x_grid + 3.0 * w && (s.get(1) >= y_grid + h && s.get(1) < y_grid + 2.0 * h)) ? E_y5 : 0.0) - s[2] * (s.get(0) >= x_grid + 0.0 * w && (s.get(0) < x_grid + w && (s.get(1) >= y_grid + 0.0 * h && s.get(1) < y_grid + h)) ? B_0 : s.get(0) >= x_grid + w && (s.get(0) < x_grid + 2.0 * w && (s.get(1) >= y_grid + 0.0 * h && s.get(1) < y_grid + h)) ? B_1 : s.get(0) >= x_grid + 2.0 * w && (s.get(0) < x_grid + 3.0 * w && (s.get(1) >= y_grid + 0.0 * h && s.get(1) < y_grid + h)) ? B_2 : s.get(0) >= x_grid + 0.0 * w && (s.get(0) < x_grid + w && (s.get(1) >= y_grid + h && s.get(1) < y_grid + 2.0 * h)) ? B_3 : s.get(0) >= x_grid + w && (s.get(0) < x_grid + 2.0 * w && (s.get(1) >= y_grid + h && s.get(1) < y_grid + 2.0 * h)) ? B_4 : s.get(0) >= x_grid + 2.0 * w && (s.get(0) < x_grid + 3.0 * w && (s.get(1) >= y_grid + h && s.get(1) < y_grid + 2.0 * h)) ? B_5 : 0.0));
    }
}
