package Trajecto;

/** \file OutputFormat.java
    \author Zhuo Zhang
    \brief Provides the function for writing outputs
    \note Generated by Drasil v0.1-alpha
*/

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;

public class OutputFormat {
    
    /** \brief Writes the output values to output.txt
        \param s dependent variables (m)
    */
    public static void write_output(ArrayList<Double> s) throws IOException {
        PrintWriter outputfile;
        outputfile = new PrintWriter(new FileWriter(new File("output.txt"), false));
        outputfile.print("s = ");
        outputfile.println(s);
        outputfile.close();
    }
}
