## \file Calculations.py
# \author Zhuo Zhang
# \brief Provides functions for calculating the outputs
# \note Generated by Drasil v0.1-alpha

import scipy.integrate

## \brief Calculates time of detector hit (s)
# \param t_final final simulation time (s)
# \return time of detector hit (s)
def func_t_hit(t_final):
    return t_final

## \brief Calculates electric field in region i (N/C)
# \param E_vect electric field vector (N/C)
# \return electric field in region i (N/C)
def func_E_vect_i(E_vect):
    return E_vect

## \brief Calculates dependent variables (m)
# \param κ charge-to-mass ratio (C/kg)
# \param E_x x-component of the electric field (N/C)
# \param B out-of-plane magnetic flux density (T)
# \param E_y y-component of the electric field (N/C)
# \param x_0 initial x-position (m)
# \param y_0 initial y-position (m)
# \param v_x0 initial x-velocity (m/s)
# \param v_y0 initial y-velocity (m/s)
# \param t_final final simulation time (s)
# \return dependent variables (m)
def func_s(κ, E_x, B, E_y, x_0, y_0, v_x0, v_y0, t_final):
    def f(t, s):
        return [s[2], s[3], κ * (E_x + s[3] * B), κ * (E_y - s[2] * B)]
    
    r = scipy.integrate.ode(f)
    r.set_integrator("dopri5", atol=1.0e-6, rtol=1.0e-6)
    r.set_initial_value([x_0, y_0, v_x0, v_y0], 0.0)
    s = [[x_0, y_0, v_x0, v_y0]]
    while r.successful() and r.t < t_final:
        r.integrate(r.t + 1.0e-9)
        s.append(r.y.tolist())
    
    return s
