## \file Constants.py
# \author Zhuo Zhang
# \brief Provides the structure for holding constant values
# \note Generated by Drasil v0.1-alpha

## \brief Structure for holding the constant values
class Constants:
    M_MIN = 1.0e-31
    M_MAX = 1.0e-25
    Q_MAX = 1.0e-15
    V_MAX = 1.0e7
    E_MAX = 1000000.0
    B_MAX = 10.0
    T_MAX = 1.0e-4
