## \file Control.py
# \author Zhuo Zhang
# \brief Controls the flow of the program
# \note Generated by Drasil v0.1-alpha

import sys

import Calculations
import InputParameters
import OutputFormat

filename = sys.argv[1]
m, q, x_0, y_0, v_x0, v_y0, E_x, E_y, B, t_final = InputParameters.get_input(filename)
κ, s_0, E_vect, B_vect = InputParameters.derived_values(q, m, x_0, y_0, v_x0, v_y0, E_x, E_y, B)
InputParameters.input_constraints(m, q, x_0, y_0, v_x0, v_y0, E_x, E_y, B, t_final)
t_hit = Calculations.func_t_hit(t_final)
E_vect_i = Calculations.func_E_vect_i(E_vect)
s = Calculations.func_s(κ, E_x, B, E_y, x_0, y_0, v_x0, v_y0, t_final)
OutputFormat.write_output(s)
