## \file Control.py
# \author Zhuo Zhang
# \brief Controls the flow of the program
# \note Generated by Drasil v0.1-alpha

import sys

import Calculations
import InputParameters
import OutputFormat

filename = sys.argv[1]
m, q, x_0, y_0, v_x0, v_y0, N, N_col, w, h, x_grid, y_grid, E_x0, E_x1, E_x2, E_x3, E_x4, E_x5, E_y0, E_y1, E_y2, E_y3, E_y4, E_y5, B_0, B_1, B_2, B_3, B_4, B_5, d_orient, x_det, y_det, y_detMin, y_detMax, x_detMin, x_detMax, t_final = InputParameters.get_input(filename)
κ, s_0, E_vect, B_vect, R_i, E_vect_i, L_det = InputParameters.derived_values(q, m, x_0, y_0, v_x0, v_y0, E_x0, E_y0, B_0, x_grid, y_grid, w, h, d_orient, x_det, y_det, y_detMin, y_detMax, x_detMin, x_detMax)
InputParameters.input_constraints(m, q, x_0, y_0, v_x0, v_y0, N, N_col, w, h, x_grid, y_grid, d_orient, x_det, y_det, y_detMin, y_detMax, x_detMin, x_detMax, t_final)
s = Calculations.func_s(κ, E_x0, E_x1, E_x2, E_x3, E_x4, E_x5, x_grid, w, y_grid, h, B_0, B_1, B_2, B_3, B_4, B_5, E_y0, E_y1, E_y2, E_y3, E_y4, E_y5, x_0, y_0, v_x0, v_y0, t_final)
t_hit = Calculations.func_t_hit(d_orient, x_det, y_det, y_detMin, y_detMax, x_detMin, x_detMax, s)
x_hit = Calculations.func_x_hit(d_orient, x_det, y_det, y_detMin, y_detMax, x_detMin, x_detMax, s)
y_hit = Calculations.func_y_hit(d_orient, x_det, y_det, y_detMin, y_detMax, x_detMin, x_detMax, s)
OutputFormat.write_output(s, t_hit, x_hit, y_hit)
