## \file DetectorHit.py
# \author Zhuo Zhang
# \brief Provides functions for detecting particle-detector line intersection
# \note Generated by Drasil v0.1-alpha

## \brief Finds time of detector hit
# \param traj trajectory
# \param d_orient detector orientation
# \param x_det detector line x-position
# \param y_det detector line y-position
# \param y_detMin detector y min
# \param y_detMax detector y max
# \param x_detMin detector x min
# \param x_detMax detector x max
# \return Finds time of detector hit
def func_t_hit(traj, d_orient, x_det, y_det, y_detMin, y_detMax, x_detMin, x_detMax):
    num_pts = len(traj)
    t_best = -1
    x_best = 0
    y_best = 0
    for i in range(0, num_pts, 1):
        x_i = traj[i][0]
        y_i = traj[i][1]
        if d_orient == 0:
            if t_best < 0 and (x_i >= x_det and (y_i >= y_detMin and y_i <= y_detMax)):
                t_best = 0
                x_best = x_i
                y_best = y_i
        else:
            if t_best < 0 and (y_i >= y_det and (x_i >= x_detMin and x_i <= x_detMax)):
                t_best = 0
                x_best = x_i
                y_best = y_i
    return t_best

## \brief Finds x-coordinate of detector hit
# \param traj trajectory
# \param d_orient detector orientation
# \param x_det detector line x-position
# \param y_det detector line y-position
# \param y_detMin detector y min
# \param y_detMax detector y max
# \param x_detMin detector x min
# \param x_detMax detector x max
# \return Finds x-coordinate of detector hit
def func_x_hit(traj, d_orient, x_det, y_det, y_detMin, y_detMax, x_detMin, x_detMax):
    num_pts = len(traj)
    t_best = -1
    x_best = 0
    y_best = 0
    for i in range(0, num_pts, 1):
        x_i = traj[i][0]
        y_i = traj[i][1]
        if d_orient == 0:
            if t_best < 0 and (x_i >= x_det and (y_i >= y_detMin and y_i <= y_detMax)):
                t_best = 0
                x_best = x_i
                y_best = y_i
        else:
            if t_best < 0 and (y_i >= y_det and (x_i >= x_detMin and x_i <= x_detMax)):
                t_best = 0
                x_best = x_i
                y_best = y_i
    return x_best

## \brief Finds y-coordinate of detector hit
# \param traj trajectory
# \param d_orient detector orientation
# \param x_det detector line x-position
# \param y_det detector line y-position
# \param y_detMin detector y min
# \param y_detMax detector y max
# \param x_detMin detector x min
# \param x_detMax detector x max
# \return Finds y-coordinate of detector hit
def func_y_hit(traj, d_orient, x_det, y_det, y_detMin, y_detMax, x_detMin, x_detMax):
    num_pts = len(traj)
    t_best = -1
    x_best = 0
    y_best = 0
    for i in range(0, num_pts, 1):
        x_i = traj[i][0]
        y_i = traj[i][1]
        if d_orient == 0:
            if t_best < 0 and (x_i >= x_det and (y_i >= y_detMin and y_i <= y_detMax)):
                t_best = 0
                x_best = x_i
                y_best = y_i
        else:
            if t_best < 0 and (y_i >= y_det and (x_i >= x_detMin and x_i <= x_detMax)):
                t_best = 0
                x_best = x_i
                y_best = y_i
    return y_best
