## \file DetectorHit.py
# \author Zhuo Zhang
# \brief Provides functions for detecting particle-detector line intersection
# \note Generated by Drasil v0.1-alpha

## \brief Internal helper: finds (t_hit, x_hit, y_hit) for a detector crossing.
#  Uses linear interpolation to find the exact crossing point.
# \param traj trajectory list of [x, y, vx, vy]
# \param d_orient 0 = vertical detector at x=d_pos, 1 = horizontal detector at y=d_pos
# \param d_pos detector line position (m)
# \param d_start detector segment start coordinate (m)
# \param d_len detector segment length (m)
# \param t_final final simulation time (s)
# \return (t_hit, x_hit, y_hit); all -1 if no hit
def _find_hit(traj, d_orient, d_pos, d_start, d_len, t_final):
    num_pts = len(traj)
    t_step = t_final / (num_pts - 1)
    x_prev = traj[0][0]
    y_prev = traj[0][1]
    for i in range(1, num_pts):
        x_i = traj[i][0]
        y_i = traj[i][1]
        if d_orient == 0:
            # Vertical detector at x = d_pos
            crossed = (x_prev < d_pos and x_i >= d_pos) or \
                      (x_prev >= d_pos and x_i < d_pos)
            if crossed and x_i != x_prev:
                frac = (d_pos - x_prev) / (x_i - x_prev)
                y_cross = y_prev + frac * (y_i - y_prev)
                if d_start <= y_cross <= d_start + d_len:
                    t_hit = (i - 1 + frac) * t_step
                    return t_hit, d_pos, y_cross
        else:
            # Horizontal detector at y = d_pos
            crossed = (y_prev < d_pos and y_i >= d_pos) or \
                      (y_prev >= d_pos and y_i < d_pos)
            if crossed and y_i != y_prev:
                frac = (d_pos - y_prev) / (y_i - y_prev)
                x_cross = x_prev + frac * (x_i - x_prev)
                if d_start <= x_cross <= d_start + d_len:
                    t_hit = (i - 1 + frac) * t_step
                    return t_hit, x_cross, d_pos
        x_prev = x_i
        y_prev = y_i
    return -1, -1, -1

## \brief Finds time of detector hit (s)
# \param traj trajectory
# \param d_orient detector orientation
# \param d_pos detector line position (m)
# \param d_start detector start coordinate (m)
# \param d_len detector line length (m)
# \param t_final final simulation time (s)
# \return time of detector hit, or -1 if no hit
def det_t_hit(traj, d_orient, d_pos, d_start, d_len, t_final):
    t, x, y = _find_hit(traj, d_orient, d_pos, d_start, d_len, t_final)
    return t

## \brief Finds x-coordinate of detector hit (m)
# \param traj trajectory
# \param d_orient detector orientation
# \param d_pos detector line position (m)
# \param d_start detector start coordinate (m)
# \param d_len detector line length (m)
# \param t_final final simulation time (s)
# \return x-coordinate of hit, or -1 if no hit
def det_x_hit(traj, d_orient, d_pos, d_start, d_len, t_final):
    t, x, y = _find_hit(traj, d_orient, d_pos, d_start, d_len, t_final)
    return x

## \brief Finds y-coordinate of detector hit (m)
# \param traj trajectory
# \param d_orient detector orientation
# \param d_pos detector line position (m)
# \param d_start detector start coordinate (m)
# \param d_len detector line length (m)
# \param t_final final simulation time (s)
# \return y-coordinate of hit, or -1 if no hit
def det_y_hit(traj, d_orient, d_pos, d_start, d_len, t_final):
    t, x, y = _find_hit(traj, d_orient, d_pos, d_start, d_len, t_final)
    return y
