## \file DetectorHit.py
# \author Zhuo Zhang
# \brief Provides functions for detecting particle-detector line intersection
# \note Generated by Drasil v0.1-alpha

## \brief Finds time of detector hit
# \param traj trajectory
# \param d_orient detector orientation
# \param d_pos detector line position
# \param d_start detector start coordinate
# \param d_len detector line length
# \param t_final final simulation time
# \return Finds time of detector hit
def det_t_hit(traj, d_orient, d_pos, d_start, d_len, t_final):
    num_pts = len(traj)
    t_best = -1
    x_best = -1
    y_best = -1
    t_step = t_final / (num_pts - 1)
    x_prev = traj[0][0]
    y_prev = traj[0][1]
    for i in range(0, num_pts, 1):
        x_i = traj[i][0]
        y_i = traj[i][1]
        if d_orient == 0:
            if t_best < 0 and ((x_prev < d_pos and x_i >= d_pos or x_prev >= d_pos and x_i < d_pos) and (y_i >= d_start and y_i <= d_start + d_len)):
                t_best = i * t_step
                x_best = x_i
                y_best = y_i
        else:
            if t_best < 0 and ((y_prev < d_pos and y_i >= d_pos or y_prev >= d_pos and y_i < d_pos) and (x_i >= d_start and x_i <= d_start + d_len)):
                t_best = i * t_step
                x_best = x_i
                y_best = y_i
        x_prev = x_i
        y_prev = y_i
    return t_best

## \brief Finds x-coordinate of detector hit
# \param traj trajectory
# \param d_orient detector orientation
# \param d_pos detector line position
# \param d_start detector start coordinate
# \param d_len detector line length
# \param t_final final simulation time
# \return Finds x-coordinate of detector hit
def det_x_hit(traj, d_orient, d_pos, d_start, d_len, t_final):
    num_pts = len(traj)
    t_best = -1
    x_best = -1
    y_best = -1
    t_step = t_final / (num_pts - 1)
    x_prev = traj[0][0]
    y_prev = traj[0][1]
    for i in range(0, num_pts, 1):
        x_i = traj[i][0]
        y_i = traj[i][1]
        if d_orient == 0:
            if t_best < 0 and ((x_prev < d_pos and x_i >= d_pos or x_prev >= d_pos and x_i < d_pos) and (y_i >= d_start and y_i <= d_start + d_len)):
                t_best = i * t_step
                x_best = x_i
                y_best = y_i
        else:
            if t_best < 0 and ((y_prev < d_pos and y_i >= d_pos or y_prev >= d_pos and y_i < d_pos) and (x_i >= d_start and x_i <= d_start + d_len)):
                t_best = i * t_step
                x_best = x_i
                y_best = y_i
        x_prev = x_i
        y_prev = y_i
    return x_best

## \brief Finds y-coordinate of detector hit
# \param traj trajectory
# \param d_orient detector orientation
# \param d_pos detector line position
# \param d_start detector start coordinate
# \param d_len detector line length
# \param t_final final simulation time
# \return Finds y-coordinate of detector hit
def det_y_hit(traj, d_orient, d_pos, d_start, d_len, t_final):
    num_pts = len(traj)
    t_best = -1
    x_best = -1
    y_best = -1
    t_step = t_final / (num_pts - 1)
    x_prev = traj[0][0]
    y_prev = traj[0][1]
    for i in range(0, num_pts, 1):
        x_i = traj[i][0]
        y_i = traj[i][1]
        if d_orient == 0:
            if t_best < 0 and ((x_prev < d_pos and x_i >= d_pos or x_prev >= d_pos and x_i < d_pos) and (y_i >= d_start and y_i <= d_start + d_len)):
                t_best = i * t_step
                x_best = x_i
                y_best = y_i
        else:
            if t_best < 0 and ((y_prev < d_pos and y_i >= d_pos or y_prev >= d_pos and y_i < d_pos) and (x_i >= d_start and x_i <= d_start + d_len)):
                t_best = i * t_step
                x_best = x_i
                y_best = y_i
        x_prev = x_i
        y_prev = y_i
    return y_best
