## \file InputParameters.py
# \author Zhuo Zhang
# \brief Provides the function for reading inputs, the function for calculating derived values, and the function for checking the physical constraints and software constraints on the input
# \note Generated by Drasil v0.1-alpha

import Constants

## \brief Reads input from a file with the given file name
# \param filename name of the input file
# \return particle mass (kg)
# \return particle charge (C)
# \return initial x-position (m)
# \return initial y-position (m)
# \return initial x-velocity (m/s)
# \return initial y-velocity (m/s)
# \return x-component of the electric field (N/C)
# \return y-component of the electric field (N/C)
# \return out-of-plane magnetic flux density (T)
# \return final simulation time (s)
def get_input(filename):
    infile = open(filename, "r")
    infile.readline()
    m = float(infile.readline())
    infile.readline()
    q = float(infile.readline())
    infile.readline()
    x_0 = float(infile.readline())
    infile.readline()
    y_0 = float(infile.readline())
    infile.readline()
    v_x0 = float(infile.readline())
    infile.readline()
    v_y0 = float(infile.readline())
    infile.readline()
    E_x = float(infile.readline())
    infile.readline()
    E_y = float(infile.readline())
    infile.readline()
    B = float(infile.readline())
    infile.readline()
    t_final = float(infile.readline())
    infile.close()
    
    return m, q, x_0, y_0, v_x0, v_y0, E_x, E_y, B, t_final

## \brief Calculates values that can be immediately derived from the inputs
# \param q particle charge (C)
# \param m particle mass (kg)
# \param x_0 initial x-position (m)
# \param y_0 initial y-position (m)
# \param v_x0 initial x-velocity (m/s)
# \param v_y0 initial y-velocity (m/s)
# \param E_x x-component of the electric field (N/C)
# \param E_y y-component of the electric field (N/C)
# \param B out-of-plane magnetic flux density (T)
# \return charge-to-mass ratio (C/kg)
# \return initial state vector
# \return electric field vector (N/C)
# \return magnetic flux density vector (T)
def derived_values(q, m, x_0, y_0, v_x0, v_y0, E_x, E_y, B):
    κ = q / m
    
    s_0 = [x_0, y_0, v_x0, v_y0]
    
    E_vect = [E_x, E_y, 0.0]
    
    B_vect = [0.0, 0.0, B]
    
    return κ, s_0, E_vect, B_vect

## \brief Verifies that input values satisfy the physical constraints and software constraints
# \param m particle mass (kg)
# \param q particle charge (C)
# \param x_0 initial x-position (m)
# \param y_0 initial y-position (m)
# \param v_x0 initial x-velocity (m/s)
# \param v_y0 initial y-velocity (m/s)
# \param E_x x-component of the electric field (N/C)
# \param E_y y-component of the electric field (N/C)
# \param B out-of-plane magnetic flux density (T)
# \param t_final final simulation time (s)
def input_constraints(m, q, x_0, y_0, v_x0, v_y0, E_x, E_y, B, t_final):
    if not(Constants.Constants.M_MIN <= m and m <= Constants.Constants.M_MAX):
        print("Warning: ", end="")
        print("m has value ", end="")
        print(m, end="")
        print(", but is suggested to be ", end="")
        print("between ", end="")
        print(Constants.Constants.M_MIN, end="")
        print(" (m_min)", end="")
        print(" and ", end="")
        print(Constants.Constants.M_MAX, end="")
        print(" (m_max)", end="")
        print(".")
    if not(-Constants.Constants.Q_MAX <= q and q <= Constants.Constants.Q_MAX):
        print("Warning: ", end="")
        print("q has value ", end="")
        print(q, end="")
        print(", but is suggested to be ", end="")
        print("between ", end="")
        print(-Constants.Constants.Q_MAX, end="")
        print(" (-q_max)", end="")
        print(" and ", end="")
        print(Constants.Constants.Q_MAX, end="")
        print(" (q_max)", end="")
        print(".")
    if not(-Constants.Constants.V_MAX <= v_x0 and v_x0 <= Constants.Constants.V_MAX):
        print("Warning: ", end="")
        print("v_x0 has value ", end="")
        print(v_x0, end="")
        print(", but is suggested to be ", end="")
        print("between ", end="")
        print(-Constants.Constants.V_MAX, end="")
        print(" (-v_max)", end="")
        print(" and ", end="")
        print(Constants.Constants.V_MAX, end="")
        print(" (v_max)", end="")
        print(".")
    if not(-Constants.Constants.V_MAX <= v_y0 and v_y0 <= Constants.Constants.V_MAX):
        print("Warning: ", end="")
        print("v_y0 has value ", end="")
        print(v_y0, end="")
        print(", but is suggested to be ", end="")
        print("between ", end="")
        print(-Constants.Constants.V_MAX, end="")
        print(" (-v_max)", end="")
        print(" and ", end="")
        print(Constants.Constants.V_MAX, end="")
        print(" (v_max)", end="")
        print(".")
    if not(-Constants.Constants.E_MAX <= E_x and E_x <= Constants.Constants.E_MAX):
        print("Warning: ", end="")
        print("E_x has value ", end="")
        print(E_x, end="")
        print(", but is suggested to be ", end="")
        print("between ", end="")
        print(-Constants.Constants.E_MAX, end="")
        print(" (-E_max)", end="")
        print(" and ", end="")
        print(Constants.Constants.E_MAX, end="")
        print(" (E_max)", end="")
        print(".")
    if not(-Constants.Constants.E_MAX <= E_y and E_y <= Constants.Constants.E_MAX):
        print("Warning: ", end="")
        print("E_y has value ", end="")
        print(E_y, end="")
        print(", but is suggested to be ", end="")
        print("between ", end="")
        print(-Constants.Constants.E_MAX, end="")
        print(" (-E_max)", end="")
        print(" and ", end="")
        print(Constants.Constants.E_MAX, end="")
        print(" (E_max)", end="")
        print(".")
    if not(-Constants.Constants.B_MAX <= B and B <= Constants.Constants.B_MAX):
        print("Warning: ", end="")
        print("B has value ", end="")
        print(B, end="")
        print(", but is suggested to be ", end="")
        print("between ", end="")
        print(-Constants.Constants.B_MAX, end="")
        print(" (-B_max)", end="")
        print(" and ", end="")
        print(Constants.Constants.B_MAX, end="")
        print(" (B_max)", end="")
        print(".")
    if not(t_final <= Constants.Constants.T_MAX):
        print("Warning: ", end="")
        print("t_final has value ", end="")
        print(t_final, end="")
        print(", but is suggested to be ", end="")
        print("below ", end="")
        print(Constants.Constants.T_MAX, end="")
        print(" (t_max)", end="")
        print(".")
    
    if not(m > 0.0):
        print("Warning: ", end="")
        print("m has value ", end="")
        print(m, end="")
        print(", but is suggested to be ", end="")
        print("above ", end="")
        print(0.0, end="")
        print(".")
    if not(t_final > 0.0):
        print("Warning: ", end="")
        print("t_final has value ", end="")
        print(t_final, end="")
        print(", but is suggested to be ", end="")
        print("above ", end="")
        print(0.0, end="")
        print(".")
