## \file OutputFormat.py
# \author Zhuo Zhang
# \brief Provides the function for writing outputs
# \note Generated by Drasil v0.1-alpha

## \brief Writes the output values to output.txt
# \param s dependent variables (m)
def write_output(s):
    outputfile = open("output.txt", "w")
    print("s = ", end="", file=outputfile)
    print(s, file=outputfile)
    outputfile.close()
