/** \file Calculations.hpp
    \author Zhuo Zhang
    \brief Provides functions for calculating the outputs
    \note Generated by Drasil v0.1-alpha
*/

#ifndef Calculations_h
#define Calculations_h

#include <vector>

#include "ODE.hpp"
#include "Populate.hpp"

using std::vector;

/** \brief Calculates dependent variables (m)
    \param κ charge-to-mass ratio (C/kg)
    \param E_x0 x-electric field in region 0 (N/C)
    \param E_x1 x-electric field in region 1 (N/C)
    \param E_x2 x-electric field in region 2 (N/C)
    \param E_x3 x-electric field in region 3 (N/C)
    \param E_x4 x-electric field in region 4 (N/C)
    \param E_x5 x-electric field in region 5 (N/C)
    \param x_grid grid origin x-coordinate (m)
    \param N_col number of grid columns
    \param w region width (m)
    \param y_grid grid origin y-coordinate (m)
    \param h region height (m)
    \param B_0 magnetic flux density in region 0 (T)
    \param B_1 magnetic flux density in region 1 (T)
    \param B_2 magnetic flux density in region 2 (T)
    \param B_3 magnetic flux density in region 3 (T)
    \param B_4 magnetic flux density in region 4 (T)
    \param B_5 magnetic flux density in region 5 (T)
    \param E_y0 y-electric field in region 0 (N/C)
    \param E_y1 y-electric field in region 1 (N/C)
    \param E_y2 y-electric field in region 2 (N/C)
    \param E_y3 y-electric field in region 3 (N/C)
    \param E_y4 y-electric field in region 4 (N/C)
    \param E_y5 y-electric field in region 5 (N/C)
    \param x_0 initial x-position (m)
    \param y_0 initial y-position (m)
    \param v_x0 initial x-velocity (m/s)
    \param v_y0 initial y-velocity (m/s)
    \param t_final final simulation time (s)
    \return dependent variables (m)
*/
vector<double> func_s(double κ, double E_x0, double E_x1, double E_x2, double E_x3, double E_x4, double E_x5, double x_grid, int N_col, double w, double y_grid, double h, double B_0, double B_1, double B_2, double B_3, double B_4, double B_5, double E_y0, double E_y1, double E_y2, double E_y3, double E_y4, double E_y5, double x_0, double y_0, double v_x0, double v_y0, double t_final);

/** \brief Calculates time of detector hit (s)
    \param d_orient detector orientation
    \param d_pos detector line position (m)
    \param d_start detector start coordinate (m)
    \param d_len detector line length (m)
    \param t_final final simulation time (s)
    \param s dependent variables (m)
    \return time of detector hit (s)
*/
double func_t_hit(int d_orient, double d_pos, double d_start, double d_len, double t_final, vector<double> &s);

/** \brief Calculates x-coordinate of impact point (m)
    \param d_orient detector orientation
    \param d_pos detector line position (m)
    \param d_start detector start coordinate (m)
    \param d_len detector line length (m)
    \param t_final final simulation time (s)
    \param s dependent variables (m)
    \return x-coordinate of impact point (m)
*/
double func_x_hit(int d_orient, double d_pos, double d_start, double d_len, double t_final, vector<double> &s);

/** \brief Calculates y-coordinate of impact point (m)
    \param d_orient detector orientation
    \param d_pos detector line position (m)
    \param d_start detector start coordinate (m)
    \param d_len detector line length (m)
    \param t_final final simulation time (s)
    \param s dependent variables (m)
    \return y-coordinate of impact point (m)
*/
double func_y_hit(int d_orient, double d_pos, double d_start, double d_len, double t_final, vector<double> &s);

#endif
