/** \file Calculations.hpp
    \author Zhuo Zhang
    \brief Provides functions for calculating the outputs
    \note Generated by Drasil v0.1-alpha
*/

#ifndef Calculations_h
#define Calculations_h

#include <vector>

#include "ODE.hpp"
#include "Populate.hpp"

using std::vector;

/** \brief Calculates time of detector hit (s)
    \param t_final final simulation time (s)
    \return time of detector hit (s)
*/
double func_t_hit(double t_final);

/** \brief Calculates electric field in region i (N/C)
    \param E_vect electric field vector (N/C)
    \return electric field in region i (N/C)
*/
double func_E_vect_i(double E_vect);

/** \brief Calculates dependent variables (m)
    \param κ charge-to-mass ratio (C/kg)
    \param E_x x-component of the electric field (N/C)
    \param B out-of-plane magnetic flux density (T)
    \param E_y y-component of the electric field (N/C)
    \param x_0 initial x-position (m)
    \param y_0 initial y-position (m)
    \param v_x0 initial x-velocity (m/s)
    \param v_y0 initial y-velocity (m/s)
    \param t_final final simulation time (s)
    \return dependent variables (m)
*/
vector<double> func_s(double κ, double E_x, double B, double E_y, double x_0, double y_0, double v_x0, double v_y0, double t_final);

#endif
