/** \file Control.cpp
    \author Zhuo Zhang
    \brief Controls the flow of the program
    \note Generated by Drasil v0.1-alpha
*/

#include <string>
#include <vector>

#include "Calculations.hpp"
#include "InputParameters.hpp"
#include "OutputFormat.hpp"

using std::string;
using std::vector;

/** \brief Controls the flow of the program
    \param argc Number of command-line arguments
    \param argv List of command-line arguments
    \return exit code
*/
int main(int argc, const char *argv[]) {
    string filename = argv[1];
    double m;
    double q;
    double x_0;
    double y_0;
    double v_x0;
    double v_y0;
    double N;
    double w;
    double h;
    double x_grid;
    double y_grid;
    double E_x;
    double E_y;
    double B;
    double d_orient;
    double x_det;
    double y_det;
    double y_min^det;
    double y_max^det;
    double x_min^det;
    double x_max^det;
    double t_final;
    double κ;
    double s_0;
    double E_vect;
    double B_vect;
    double R_i;
    double E_vect_i;
    double L_det;
    get_input(filename, m, q, x_0, y_0, v_x0, v_y0, N, w, h, x_grid, y_grid, E_x, E_y, B, d_orient, x_det, y_det, y_min^det, y_max^det, x_min^det, x_max^det, t_final);
    derived_values(q, m, x_0, y_0, v_x0, v_y0, E_x, E_y, B, x_grid, y_grid, w, h, d_orient, x_det, y_det, y_min^det, y_max^det, x_min^det, x_max^det, κ, s_0, E_vect, B_vect, R_i, E_vect_i, L_det);
    input_constraints(m, q, x_0, y_0, v_x0, v_y0, N, w, h, x_grid, y_grid, E_x, E_y, B, d_orient, x_det, y_det, y_min^det, y_max^det, x_min^det, x_max^det, t_final);
    vector<vector<double>> s = func_s(κ, E_x, B, E_y, x_0, y_0, v_x0, v_y0, t_final);
    write_output(s);
    
    return 0;
}
