/** \file Control.cpp
    \author Zhuo Zhang
    \brief Controls the flow of the program
    \note Generated by Drasil v0.1-alpha
*/

#include <string>
#include <vector>

#include "Calculations.hpp"
#include "InputParameters.hpp"
#include "OutputFormat.hpp"

using std::string;
using std::vector;

/** \brief Controls the flow of the program
    \param argc Number of command-line arguments
    \param argv List of command-line arguments
    \return exit code
*/
int main(int argc, const char *argv[]) {
    string filename = argv[1];
    double m;
    double q;
    double x_0;
    double y_0;
    double v_x0;
    double v_y0;
    double E_x;
    double E_y;
    double B;
    double t_final;
    double κ;
    double s_0;
    double E_vect;
    double B_vect;
    get_input(filename, m, q, x_0, y_0, v_x0, v_y0, E_x, E_y, B, t_final);
    derived_values(q, m, x_0, y_0, v_x0, v_y0, E_x, E_y, B, κ, s_0, E_vect, B_vect);
    input_constraints(m, q, x_0, y_0, v_x0, v_y0, E_x, E_y, B, t_final);
    double t_hit = func_t_hit(t_final);
    double E_vect_i = func_E_vect_i(E_vect);
    vector<double> s = func_s(κ, E_x, B, E_y, x_0, y_0, v_x0, v_y0, t_final);
    write_output(s);
    
    return 0;
}
