/** \file Control.cpp
    \author Zhuo Zhang
    \brief Controls the flow of the program
    \note Generated by Drasil v0.1-alpha
*/

#include <string>
#include <vector>

#include "Calculations.hpp"
#include "InputParameters.hpp"
#include "OutputFormat.hpp"

using std::string;
using std::vector;

/** \brief Controls the flow of the program
    \param argc Number of command-line arguments
    \param argv List of command-line arguments
    \return exit code
*/
int main(int argc, const char *argv[]) {
    string filename = argv[1];
    double m;
    double q;
    double x_0;
    double y_0;
    double v_x0;
    double v_y0;
    int N;
    int N_col;
    double w;
    double h;
    double x_grid;
    double y_grid;
    double E_x0;
    double E_x1;
    double E_x2;
    double E_x3;
    double E_x4;
    double E_x5;
    double E_y0;
    double E_y1;
    double E_y2;
    double E_y3;
    double E_y4;
    double E_y5;
    double B_0;
    double B_1;
    double B_2;
    double B_3;
    double B_4;
    double B_5;
    int d_orient;
    double d_pos;
    double d_start;
    double d_len;
    double t_final;
    double κ;
    double s_0;
    double E_vect;
    double B_vect;
    double R_i;
    double E_vect_i;
    get_input(filename, m, q, x_0, y_0, v_x0, v_y0, N, N_col, w, h, x_grid, y_grid, E_x0, E_x1, E_x2, E_x3, E_x4, E_x5, E_y0, E_y1, E_y2, E_y3, E_y4, E_y5, B_0, B_1, B_2, B_3, B_4, B_5, d_orient, d_pos, d_start, d_len, t_final);
    derived_values(d_orient, q, m, x_0, y_0, v_x0, v_y0, E_x0, E_y0, B_0, x_grid, y_grid, w, h, κ, s_0, E_vect, B_vect, R_i, E_vect_i);
    input_constraints(m, q, x_0, y_0, v_x0, v_y0, N, N_col, w, h, x_grid, y_grid, d_orient, d_pos, d_start, d_len, t_final);
    vector<double> s = func_s(κ, E_x0, E_x1, E_x2, E_x3, E_x4, E_x5, x_grid, N_col, w, y_grid, h, B_0, B_1, B_2, B_3, B_4, B_5, E_y0, E_y1, E_y2, E_y3, E_y4, E_y5, x_0, y_0, v_x0, v_y0, t_final);
    double t_hit = func_t_hit(d_orient, d_pos, d_start, d_len, t_final, s);
    double x_hit = func_x_hit(d_orient, d_pos, d_start, d_len, t_final, s);
    double y_hit = func_y_hit(d_orient, d_pos, d_start, d_len, t_final, s);
    write_output(s, t_hit, x_hit, y_hit);
    
    return 0;
}
