/** \file DetectorHit.hpp
    \author Zhuo Zhang
    \brief Provides functions for detecting particle-detector line intersection
    \note Generated by Drasil v0.1-alpha
*/

#ifndef DetectorHit_h
#define DetectorHit_h

#include <vector>

using std::vector;

/** \brief Finds time of detector hit
    \param traj trajectory
    \param d_orient detector orientation
    \param d_pos detector line position
    \param d_start detector start coordinate
    \param d_len detector line length
    \param t_final final simulation time
    \return Finds time of detector hit
*/
double func_t_hit(vector<vector<double>> &traj, int d_orient, double d_pos, double d_start, double d_len, double t_final);

/** \brief Finds x-coordinate of detector hit
    \param traj trajectory
    \param d_orient detector orientation
    \param d_pos detector line position
    \param d_start detector start coordinate
    \param d_len detector line length
    \param t_final final simulation time
    \return Finds x-coordinate of detector hit
*/
double func_x_hit(vector<vector<double>> &traj, int d_orient, double d_pos, double d_start, double d_len, double t_final);

/** \brief Finds y-coordinate of detector hit
    \param traj trajectory
    \param d_orient detector orientation
    \param d_pos detector line position
    \param d_start detector start coordinate
    \param d_len detector line length
    \param t_final final simulation time
    \return Finds y-coordinate of detector hit
*/
double func_y_hit(vector<vector<double>> &traj, int d_orient, double d_pos, double d_start, double d_len, double t_final);

#endif
