/** \file DetectorHit.hpp
    \author Zhuo Zhang
    \brief Provides functions for detecting particle-detector line intersection
    \note Generated by Drasil v0.1-alpha
*/

#ifndef DetectorHit_h
#define DetectorHit_h

#include <vector>

using std::vector;

/** \brief Finds time of detector hit
    \param traj trajectory
    \param d_orient detector orientation
    \param x_det detector line x-position
    \param y_det detector line y-position
    \param y_detMin detector y min
    \param y_detMax detector y max
    \param x_detMin detector x min
    \param x_detMax detector x max
    \return Finds time of detector hit
*/
double func_t_hit(vector<vector<double>> &traj, int d_orient, double x_det, double y_det, double y_detMin, double y_detMax, double x_detMin, double x_detMax);

/** \brief Finds x-coordinate of detector hit
    \param traj trajectory
    \param d_orient detector orientation
    \param x_det detector line x-position
    \param y_det detector line y-position
    \param y_detMin detector y min
    \param y_detMax detector y max
    \param x_detMin detector x min
    \param x_detMax detector x max
    \return Finds x-coordinate of detector hit
*/
double func_x_hit(vector<vector<double>> &traj, int d_orient, double x_det, double y_det, double y_detMin, double y_detMax, double x_detMin, double x_detMax);

/** \brief Finds y-coordinate of detector hit
    \param traj trajectory
    \param d_orient detector orientation
    \param x_det detector line x-position
    \param y_det detector line y-position
    \param y_detMin detector y min
    \param y_detMax detector y max
    \param x_detMin detector x min
    \param x_detMax detector x max
    \return Finds y-coordinate of detector hit
*/
double func_y_hit(vector<vector<double>> &traj, int d_orient, double x_det, double y_det, double y_detMin, double y_detMax, double x_detMin, double x_detMax);

#endif
