/** \file InputParameters.hpp
    \author Zhuo Zhang
    \brief Provides the function for reading inputs, the function for calculating derived values, and the function for checking the physical constraints and software constraints on the input
    \note Generated by Drasil v0.1-alpha
*/

#ifndef InputParameters_h
#define InputParameters_h

#include <string>

#include "Constants.hpp"

using std::ifstream;
using std::string;

/** \brief Reads input from a file with the given file name
    \param filename name of the input file
    \param m particle mass (kg)
    \param q particle charge (C)
    \param x_0 initial x-position (m)
    \param y_0 initial y-position (m)
    \param v_x0 initial x-velocity (m/s)
    \param v_y0 initial y-velocity (m/s)
    \param E_x x-component of the electric field (N/C)
    \param E_y y-component of the electric field (N/C)
    \param B out-of-plane magnetic flux density (T)
    \param t_final final simulation time (s)
*/
void get_input(string filename, double &m, double &q, double &x_0, double &y_0, double &v_x0, double &v_y0, double &E_x, double &E_y, double &B, double &t_final);

/** \brief Calculates values that can be immediately derived from the inputs
    \param q particle charge (C)
    \param m particle mass (kg)
    \param x_0 initial x-position (m)
    \param y_0 initial y-position (m)
    \param v_x0 initial x-velocity (m/s)
    \param v_y0 initial y-velocity (m/s)
    \param E_x x-component of the electric field (N/C)
    \param E_y y-component of the electric field (N/C)
    \param B out-of-plane magnetic flux density (T)
    \param κ charge-to-mass ratio (C/kg)
    \param s_0 initial state vector
    \param E_vect electric field vector (N/C)
    \param B_vect magnetic flux density vector (T)
*/
void derived_values(double q, double m, double x_0, double y_0, double v_x0, double v_y0, double E_x, double E_y, double B, double &κ, double &s_0, double &E_vect, double &B_vect);

/** \brief Verifies that input values satisfy the physical constraints and software constraints
    \param m particle mass (kg)
    \param q particle charge (C)
    \param x_0 initial x-position (m)
    \param y_0 initial y-position (m)
    \param v_x0 initial x-velocity (m/s)
    \param v_y0 initial y-velocity (m/s)
    \param E_x x-component of the electric field (N/C)
    \param E_y y-component of the electric field (N/C)
    \param B out-of-plane magnetic flux density (T)
    \param t_final final simulation time (s)
*/
void input_constraints(double m, double q, double x_0, double y_0, double v_x0, double v_y0, double E_x, double E_y, double B, double t_final);

#endif
