/** \file InputParameters.hpp
    \author Zhuo Zhang
    \brief Provides the function for reading inputs, the function for calculating derived values, and the function for checking the physical constraints and software constraints on the input
    \note Generated by Drasil v0.1-alpha
*/

#ifndef InputParameters_h
#define InputParameters_h

#include <string>

#include "Constants.hpp"

using std::ifstream;
using std::string;

/** \brief Reads input from a file with the given file name
    \param filename name of the input file
    \param m particle mass (kg)
    \param q particle charge (C)
    \param x_0 initial x-position (m)
    \param y_0 initial y-position (m)
    \param v_x0 initial x-velocity (m/s)
    \param v_y0 initial y-velocity (m/s)
    \param N number of field regions
    \param N_col number of grid columns
    \param w region width (m)
    \param h region height (m)
    \param x_grid grid origin x-coordinate (m)
    \param y_grid grid origin y-coordinate (m)
    \param E_x0 x-electric field in region 0 (N/C)
    \param E_x1 x-electric field in region 1 (N/C)
    \param E_x2 x-electric field in region 2 (N/C)
    \param E_x3 x-electric field in region 3 (N/C)
    \param E_x4 x-electric field in region 4 (N/C)
    \param E_x5 x-electric field in region 5 (N/C)
    \param E_y0 y-electric field in region 0 (N/C)
    \param E_y1 y-electric field in region 1 (N/C)
    \param E_y2 y-electric field in region 2 (N/C)
    \param E_y3 y-electric field in region 3 (N/C)
    \param E_y4 y-electric field in region 4 (N/C)
    \param E_y5 y-electric field in region 5 (N/C)
    \param B_0 magnetic flux density in region 0 (T)
    \param B_1 magnetic flux density in region 1 (T)
    \param B_2 magnetic flux density in region 2 (T)
    \param B_3 magnetic flux density in region 3 (T)
    \param B_4 magnetic flux density in region 4 (T)
    \param B_5 magnetic flux density in region 5 (T)
    \param d_orient detector orientation
    \param d_pos detector line position (m)
    \param d_start detector start coordinate (m)
    \param d_len detector line length (m)
    \param t_final final simulation time (s)
*/
void get_input(string filename, double &m, double &q, double &x_0, double &y_0, double &v_x0, double &v_y0, int &N, int &N_col, double &w, double &h, double &x_grid, double &y_grid, double &E_x0, double &E_x1, double &E_x2, double &E_x3, double &E_x4, double &E_x5, double &E_y0, double &E_y1, double &E_y2, double &E_y3, double &E_y4, double &E_y5, double &B_0, double &B_1, double &B_2, double &B_3, double &B_4, double &B_5, int &d_orient, double &d_pos, double &d_start, double &d_len, double &t_final);

/** \brief Calculates values that can be immediately derived from the inputs
    \param d_orient detector orientation
    \param q particle charge (C)
    \param m particle mass (kg)
    \param x_0 initial x-position (m)
    \param y_0 initial y-position (m)
    \param v_x0 initial x-velocity (m/s)
    \param v_y0 initial y-velocity (m/s)
    \param E_x0 x-electric field in region 0 (N/C)
    \param E_y0 y-electric field in region 0 (N/C)
    \param B_0 magnetic flux density in region 0 (T)
    \param x_grid grid origin x-coordinate (m)
    \param y_grid grid origin y-coordinate (m)
    \param w region width (m)
    \param h region height (m)
    \param κ charge-to-mass ratio (C/kg)
    \param s_0 initial state vector
    \param E_vect electric field vector (N/C)
    \param B_vect magnetic flux density vector (T)
    \param R_i rectangular field region
    \param E_vect_i electric field in region i (N/C)
*/
void derived_values(int &d_orient, double q, double m, double x_0, double y_0, double v_x0, double v_y0, double E_x0, double E_y0, double B_0, double x_grid, double y_grid, double w, double h, double &κ, double &s_0, double &E_vect, double &B_vect, double &R_i, double &E_vect_i);

/** \brief Verifies that input values satisfy the physical constraints and software constraints
    \param m particle mass (kg)
    \param q particle charge (C)
    \param x_0 initial x-position (m)
    \param y_0 initial y-position (m)
    \param v_x0 initial x-velocity (m/s)
    \param v_y0 initial y-velocity (m/s)
    \param N number of field regions
    \param N_col number of grid columns
    \param w region width (m)
    \param h region height (m)
    \param x_grid grid origin x-coordinate (m)
    \param y_grid grid origin y-coordinate (m)
    \param d_orient detector orientation
    \param d_pos detector line position (m)
    \param d_start detector start coordinate (m)
    \param d_len detector line length (m)
    \param t_final final simulation time (s)
*/
void input_constraints(double m, double q, double x_0, double y_0, double v_x0, double v_y0, int N, int N_col, double w, double h, double x_grid, double y_grid, int d_orient, double d_pos, double d_start, double d_len, double t_final);

#endif
