#include "ODE.hpp"

#include <vector>

using std::vector;

ODE::ODE(double κ, double E_x0, double E_x1, double E_x2, double E_x3, double E_x4, double E_x5, double E_y0, double E_y1, double E_y2, double E_y3, double E_y4, double E_y5, double B_0, double B_1, double B_2, double B_3, double B_4, double B_5, double x_grid, double y_grid, double w, double h, int N_col) : κ(κ), E_x0(E_x0), E_x1(E_x1), E_x2(E_x2), E_x3(E_x3), E_x4(E_x4), E_x5(E_x5), E_y0(E_y0), E_y1(E_y1), E_y2(E_y2), E_y3(E_y3), E_y4(E_y4), E_y5(E_y5), B_0(B_0), B_1(B_1), B_2(B_2), B_3(B_3), B_4(B_4), B_5(B_5), x_grid(x_grid), y_grid(y_grid), w(w), h(h), N_col(N_col) {
}

void ODE::operator()(vector<double> s, vector<double> &ds, double t) {
    ds.at(0) = s.at(2);
    ds.at(1) = s.at(3);
    ds.at(2) = κ * ((s.at(0) >= x_grid + 0 % N_col * w && (s.at(0) < x_grid + (0 % N_col + 1) * w && (s.at(1) >= y_grid + 0 / N_col * h && s.at(1) < y_grid + (0 / N_col + 1) * h)) ? E_x0 : s.at(0) >= x_grid + 1 % N_col * w && (s.at(0) < x_grid + (1 % N_col + 1) * w && (s.at(1) >= y_grid + 1 / N_col * h && s.at(1) < y_grid + (1 / N_col + 1) * h)) ? E_x1 : s.at(0) >= x_grid + 2 % N_col * w && (s.at(0) < x_grid + (2 % N_col + 1) * w && (s.at(1) >= y_grid + 2 / N_col * h && s.at(1) < y_grid + (2 / N_col + 1) * h)) ? E_x2 : s.at(0) >= x_grid + 3 % N_col * w && (s.at(0) < x_grid + (3 % N_col + 1) * w && (s.at(1) >= y_grid + 3 / N_col * h && s.at(1) < y_grid + (3 / N_col + 1) * h)) ? E_x3 : s.at(0) >= x_grid + 4 % N_col * w && (s.at(0) < x_grid + (4 % N_col + 1) * w && (s.at(1) >= y_grid + 4 / N_col * h && s.at(1) < y_grid + (4 / N_col + 1) * h)) ? E_x4 : s.at(0) >= x_grid + 5 % N_col * w && (s.at(0) < x_grid + (5 % N_col + 1) * w && (s.at(1) >= y_grid + 5 / N_col * h && s.at(1) < y_grid + (5 / N_col + 1) * h)) ? E_x5 : 0.0) + s.at(3) * (s.at(0) >= x_grid + 0 % N_col * w && (s.at(0) < x_grid + (0 % N_col + 1) * w && (s.at(1) >= y_grid + 0 / N_col * h && s.at(1) < y_grid + (0 / N_col + 1) * h)) ? B_0 : s.at(0) >= x_grid + 1 % N_col * w && (s.at(0) < x_grid + (1 % N_col + 1) * w && (s.at(1) >= y_grid + 1 / N_col * h && s.at(1) < y_grid + (1 / N_col + 1) * h)) ? B_1 : s.at(0) >= x_grid + 2 % N_col * w && (s.at(0) < x_grid + (2 % N_col + 1) * w && (s.at(1) >= y_grid + 2 / N_col * h && s.at(1) < y_grid + (2 / N_col + 1) * h)) ? B_2 : s.at(0) >= x_grid + 3 % N_col * w && (s.at(0) < x_grid + (3 % N_col + 1) * w && (s.at(1) >= y_grid + 3 / N_col * h && s.at(1) < y_grid + (3 / N_col + 1) * h)) ? B_3 : s.at(0) >= x_grid + 4 % N_col * w && (s.at(0) < x_grid + (4 % N_col + 1) * w && (s.at(1) >= y_grid + 4 / N_col * h && s.at(1) < y_grid + (4 / N_col + 1) * h)) ? B_4 : s.at(0) >= x_grid + 5 % N_col * w && (s.at(0) < x_grid + (5 % N_col + 1) * w && (s.at(1) >= y_grid + 5 / N_col * h && s.at(1) < y_grid + (5 / N_col + 1) * h)) ? B_5 : 0.0));
    ds.at(3) = κ * ((s.at(0) >= x_grid + 0 % N_col * w && (s.at(0) < x_grid + (0 % N_col + 1) * w && (s.at(1) >= y_grid + 0 / N_col * h && s.at(1) < y_grid + (0 / N_col + 1) * h)) ? E_y0 : s.at(0) >= x_grid + 1 % N_col * w && (s.at(0) < x_grid + (1 % N_col + 1) * w && (s.at(1) >= y_grid + 1 / N_col * h && s.at(1) < y_grid + (1 / N_col + 1) * h)) ? E_y1 : s.at(0) >= x_grid + 2 % N_col * w && (s.at(0) < x_grid + (2 % N_col + 1) * w && (s.at(1) >= y_grid + 2 / N_col * h && s.at(1) < y_grid + (2 / N_col + 1) * h)) ? E_y2 : s.at(0) >= x_grid + 3 % N_col * w && (s.at(0) < x_grid + (3 % N_col + 1) * w && (s.at(1) >= y_grid + 3 / N_col * h && s.at(1) < y_grid + (3 / N_col + 1) * h)) ? E_y3 : s.at(0) >= x_grid + 4 % N_col * w && (s.at(0) < x_grid + (4 % N_col + 1) * w && (s.at(1) >= y_grid + 4 / N_col * h && s.at(1) < y_grid + (4 / N_col + 1) * h)) ? E_y4 : s.at(0) >= x_grid + 5 % N_col * w && (s.at(0) < x_grid + (5 % N_col + 1) * w && (s.at(1) >= y_grid + 5 / N_col * h && s.at(1) < y_grid + (5 / N_col + 1) * h)) ? E_y5 : 0.0) - s.at(2) * (s.at(0) >= x_grid + 0 % N_col * w && (s.at(0) < x_grid + (0 % N_col + 1) * w && (s.at(1) >= y_grid + 0 / N_col * h && s.at(1) < y_grid + (0 / N_col + 1) * h)) ? B_0 : s.at(0) >= x_grid + 1 % N_col * w && (s.at(0) < x_grid + (1 % N_col + 1) * w && (s.at(1) >= y_grid + 1 / N_col * h && s.at(1) < y_grid + (1 / N_col + 1) * h)) ? B_1 : s.at(0) >= x_grid + 2 % N_col * w && (s.at(0) < x_grid + (2 % N_col + 1) * w && (s.at(1) >= y_grid + 2 / N_col * h && s.at(1) < y_grid + (2 / N_col + 1) * h)) ? B_2 : s.at(0) >= x_grid + 3 % N_col * w && (s.at(0) < x_grid + (3 % N_col + 1) * w && (s.at(1) >= y_grid + 3 / N_col * h && s.at(1) < y_grid + (3 / N_col + 1) * h)) ? B_3 : s.at(0) >= x_grid + 4 % N_col * w && (s.at(0) < x_grid + (4 % N_col + 1) * w && (s.at(1) >= y_grid + 4 / N_col * h && s.at(1) < y_grid + (4 / N_col + 1) * h)) ? B_4 : s.at(0) >= x_grid + 5 % N_col * w && (s.at(0) < x_grid + (5 % N_col + 1) * w && (s.at(1) >= y_grid + 5 / N_col * h && s.at(1) < y_grid + (5 / N_col + 1) * h)) ? B_5 : 0.0));
}
