/** \file ODE.hpp
    \author Zhuo Zhang
    \brief Class representing an ODE system
    \note Generated by Drasil v0.1-alpha
*/

#ifndef ODE_h
#define ODE_h

#include <vector>

using std::vector;

/** \brief Class representing an ODE system
*/
class ODE {
    public:
        /** \brief Constructor for ODE objects
            \param κ charge-to-mass ratio (C/kg)
            \param E_x x-component of the electric field (N/C)
            \param E_y y-component of the electric field (N/C)
            \param B out-of-plane magnetic flux density (T)
        */
        ODE(double κ, double E_x, double E_y, double B);
        /** \brief function representation of ODE system
            \param s dependent variables (m)
            \param ds change in dependent variables (m)
            \param t current independent variable value in ODE solution
        */
        void operator()(vector<double> s, vector<double> &ds, double t);
    
    private:
        double κ;
        double E_x;
        double E_y;
        double B;
        
};

#endif
