/** \file OutputFormat.hpp
    \author Zhuo Zhang
    \brief Provides the function for writing outputs
    \note Generated by Drasil v0.1-alpha
*/

#ifndef OutputFormat_h
#define OutputFormat_h

#include <string>
#include <vector>

using std::ofstream;
using std::string;
using std::vector;

/** \brief Writes the output values to output.txt
    \param s dependent variables (m)
    \param t_hit time of detector hit (s)
    \param x_hit x-coordinate of impact point (m)
    \param y_hit y-coordinate of impact point (m)
*/
void write_output(vector<double> &s, double t_hit, double x_hit, double y_hit);

#endif
