/** \file Calculations.cs
    \author Zhuo Zhang
    \brief Provides functions for calculating the outputs
    \note Generated by Drasil v0.1-alpha
*/

using System;
using System.Collections.Generic;
using Microsoft.Research.Oslo;

public class Calculations {
    
    /** \brief Calculates time of detector hit (s)
        \param t_final final simulation time (s)
        \return time of detector hit (s)
    */
    public static double func_t_hit(double t_final) {
        return t_final;
    }
    
    /** \brief Calculates electric field in region i (N/C)
        \param E_vect electric field vector (N/C)
        \return electric field in region i (N/C)
    */
    public static double func_E_vect_i(double E_vect) {
        return E_vect;
    }
    
    /** \brief Calculates dependent variables (m)
        \param κ charge-to-mass ratio (C/kg)
        \param E_x x-component of the electric field (N/C)
        \param B out-of-plane magnetic flux density (T)
        \param E_y y-component of the electric field (N/C)
        \param x_0 initial x-position (m)
        \param y_0 initial y-position (m)
        \param v_x0 initial x-velocity (m/s)
        \param v_y0 initial y-velocity (m/s)
        \param t_final final simulation time (s)
        \return dependent variables (m)
    */
    public static List<List<double>> func_s(double κ, double E_x, double B, double E_y, double x_0, double y_0, double v_x0, double v_y0, double t_final) {
        List<List<double>> s;
        Func<double, Vector, Vector> f = (t, s_vec) => {
            return new Vector(s_vec[2], s_vec[3], κ * (E_x + s_vec[3] * B), κ * (E_y - s_vec[2] * B));
        };
        Options opts = new Options();
        opts.AbsoluteTolerance = 1.0e-6;
        opts.RelativeTolerance = 1.0e-6;
        
        Vector initv = new Vector(new double[] {x_0, y_0, v_x0, v_y0});
        IEnumerable<SolPoint> sol = Ode.RK547M(0.0, initv, f, opts);
        IEnumerable<SolPoint> points = sol.SolveFromToStep(0.0, t_final, 1.0e-9);
        s = new List<List<double>> {};
        foreach (SolPoint sp in points) {
            List<double> xTemp = new List<double>(0);
            for (int i = 0; i < 4; i += 1) {
                xTemp.Add(sp.X[i]);
            }
            s.Add(xTemp);
        }
        
        return s;
    }
}
