/** \file Constants.cs
    \author Zhuo Zhang
    \brief Provides the structure for holding constant values
    \note Generated by Drasil v0.1-alpha
*/

/** \brief Structure for holding the constant values
*/
public class Constants {
    public const double m_min = 1.0e-31;
    public const double m_max = 1.0e-25;
    public const double q_max = 1.0e-15;
    public const double v_max = 1.0e7;
    public const double E_max = 1000000.0;
    public const double B_max = 10.0;
    public const double t_max = 1.0e-4;
    
}
