/** \file Control.cs
    \author Zhuo Zhang
    \brief Controls the flow of the program
    \note Generated by Drasil v0.1-alpha
*/

using System.Collections.Generic;

public class Control {
    
    /** \brief Controls the flow of the program
        \param args List of command-line arguments
    */
    public static void Main(string[] args) {
        string filename = args[0];
        double m;
        double q;
        double x_0;
        double y_0;
        double v_x0;
        double v_y0;
        double E_x;
        double E_y;
        double B;
        double t_final;
        double κ;
        double s_0;
        double E_vect;
        double B_vect;
        InputParameters.get_input(filename, out m, out q, out x_0, out y_0, out v_x0, out v_y0, out E_x, out E_y, out B, out t_final);
        InputParameters.derived_values(q, m, x_0, y_0, v_x0, v_y0, E_x, E_y, B, out κ, out s_0, out E_vect, out B_vect);
        InputParameters.input_constraints(m, q, x_0, y_0, v_x0, v_y0, E_x, E_y, B, t_final);
        double t_hit = Calculations.func_t_hit(t_final);
        double E_vect_i = Calculations.func_E_vect_i(E_vect);
        List<double> s = Calculations.func_s(κ, E_x, B, E_y, x_0, y_0, v_x0, v_y0, t_final);
        OutputFormat.write_output(s);
    }
}
