/** \file Control.cs
    \author Zhuo Zhang
    \brief Controls the flow of the program
    \note Generated by Drasil v0.1-alpha
*/

using System.Collections.Generic;

public class Control {
    
    /** \brief Controls the flow of the program
        \param args List of command-line arguments
    */
    public static void Main(string[] args) {
        string filename = args[0];
        double m;
        double q;
        double x_0;
        double y_0;
        double v_x0;
        double v_y0;
        int N;
        int N_col;
        double w;
        double h;
        double x_grid;
        double y_grid;
        double E_x0;
        double E_x1;
        double E_x2;
        double E_x3;
        double E_x4;
        double E_x5;
        double E_y0;
        double E_y1;
        double E_y2;
        double E_y3;
        double E_y4;
        double E_y5;
        double B_0;
        double B_1;
        double B_2;
        double B_3;
        double B_4;
        double B_5;
        int d_orient;
        double d_pos;
        double d_start;
        double d_len;
        double t_final;
        double κ;
        double s_0;
        double E_vect;
        double B_vect;
        double R_i;
        double E_vect_i;
        InputParameters.get_input(filename, out m, out q, out x_0, out y_0, out v_x0, out v_y0, out N, out N_col, out w, out h, out x_grid, out y_grid, out E_x0, out E_x1, out E_x2, out E_x3, out E_x4, out E_x5, out E_y0, out E_y1, out E_y2, out E_y3, out E_y4, out E_y5, out B_0, out B_1, out B_2, out B_3, out B_4, out B_5, out d_orient, out d_pos, out d_start, out d_len, out t_final);
        InputParameters.derived_values(ref d_orient, q, m, x_0, y_0, v_x0, v_y0, E_x0, E_y0, B_0, x_grid, y_grid, w, h, out κ, out s_0, out E_vect, out B_vect, out R_i, out E_vect_i);
        InputParameters.input_constraints(m, q, x_0, y_0, v_x0, v_y0, N, N_col, w, h, x_grid, y_grid, d_orient, d_pos, d_start, d_len, t_final);
        List<double> s = Calculations.func_s(κ, E_x0, E_x1, E_x2, E_x3, E_x4, E_x5, x_grid, N_col, w, y_grid, h, B_0, B_1, B_2, B_3, B_4, B_5, E_y0, E_y1, E_y2, E_y3, E_y4, E_y5, x_0, y_0, v_x0, v_y0, t_final);
        double t_hit = Calculations.func_t_hit(d_orient, d_pos, d_start, d_len, t_final, s);
        double x_hit = Calculations.func_x_hit(d_orient, d_pos, d_start, d_len, t_final, s);
        double y_hit = Calculations.func_y_hit(d_orient, d_pos, d_start, d_len, t_final, s);
        OutputFormat.write_output(s, t_hit, x_hit, y_hit);
    }
}
