/** \file Control.cs
    \author Zhuo Zhang
    \brief Controls the flow of the program
    \note Generated by Drasil v0.1-alpha
*/

using System.Collections.Generic;

public class Control {
    
    /** \brief Controls the flow of the program
        \param args List of command-line arguments
    */
    public static void Main(string[] args) {
        string filename = args[0];
        double m;
        double q;
        double x_0;
        double y_0;
        double v_x0;
        double v_y0;
        double N;
        double w;
        double h;
        double x_grid;
        double y_grid;
        double E_x;
        double E_y;
        double B;
        double d_orient;
        double x_det;
        double y_det;
        double y_min^det;
        double y_max^det;
        double x_min^det;
        double x_max^det;
        double t_final;
        double κ;
        double s_0;
        double E_vect;
        double B_vect;
        double R_i;
        double E_vect_i;
        double L_det;
        InputParameters.get_input(filename, out m, out q, out x_0, out y_0, out v_x0, out v_y0, out N, out w, out h, out x_grid, out y_grid, out E_x, out E_y, out B, out d_orient, out x_det, out y_det, out y_min^det, out y_max^det, out x_min^det, out x_max^det, out t_final);
        InputParameters.derived_values(q, m, x_0, y_0, v_x0, v_y0, E_x, E_y, B, x_grid, y_grid, w, h, d_orient, x_det, y_det, y_min^det, y_max^det, x_min^det, x_max^det, out κ, out s_0, out E_vect, out B_vect, out R_i, out E_vect_i, out L_det);
        InputParameters.input_constraints(m, q, x_0, y_0, v_x0, v_y0, N, w, h, x_grid, y_grid, E_x, E_y, B, d_orient, x_det, y_det, y_min^det, y_max^det, x_min^det, x_max^det, t_final);
        List<List<double>> s = Calculations.func_s(κ, E_x, B, E_y, x_0, y_0, v_x0, v_y0, t_final);
        OutputFormat.write_output(s);
    }
}
