/** \file DetectorHit.cs
    \author Zhuo Zhang
    \brief Provides functions for detecting particle-detector line intersection
    \note Generated by Drasil v0.1-alpha
*/

using System;
using System.Collections.Generic;

public class DetectorHit {
    
    /** \brief Finds time of detector hit
        \param traj trajectory
        \param d_orient detector orientation
        \param x_det detector line x-position
        \param y_det detector line y-position
        \param y_detMin detector y min
        \param y_detMax detector y max
        \param x_detMin detector x min
        \param x_detMax detector x max
        \return Finds time of detector hit
    */
    public static double func_t_hit(List<List<double>> traj, int d_orient, double x_det, double y_det, double y_detMin, double y_detMax, double x_detMin, double x_detMax) {
        int num_pts = traj.Count;
        double t_best = -1;
        double x_best = 0;
        double y_best = 0;
        for (int i = 0; i < num_pts; i += 1) {
            double x_i = traj[i][0];
            double y_i = traj[i][1];
            if (d_orient == 0) {
                if (t_best < 0 && (x_i >= x_det && (y_i >= y_detMin && y_i <= y_detMax))) {
                    t_best = 0;
                    x_best = x_i;
                    y_best = y_i;
                }
            }
            else {
                if (t_best < 0 && (y_i >= y_det && (x_i >= x_detMin && x_i <= x_detMax))) {
                    t_best = 0;
                    x_best = x_i;
                    y_best = y_i;
                }
            }
        }
        return t_best;
    }
    
    /** \brief Finds x-coordinate of detector hit
        \param traj trajectory
        \param d_orient detector orientation
        \param x_det detector line x-position
        \param y_det detector line y-position
        \param y_detMin detector y min
        \param y_detMax detector y max
        \param x_detMin detector x min
        \param x_detMax detector x max
        \return Finds x-coordinate of detector hit
    */
    public static double func_x_hit(List<List<double>> traj, int d_orient, double x_det, double y_det, double y_detMin, double y_detMax, double x_detMin, double x_detMax) {
        int num_pts = traj.Count;
        double t_best = -1;
        double x_best = 0;
        double y_best = 0;
        for (int i = 0; i < num_pts; i += 1) {
            double x_i = traj[i][0];
            double y_i = traj[i][1];
            if (d_orient == 0) {
                if (t_best < 0 && (x_i >= x_det && (y_i >= y_detMin && y_i <= y_detMax))) {
                    t_best = 0;
                    x_best = x_i;
                    y_best = y_i;
                }
            }
            else {
                if (t_best < 0 && (y_i >= y_det && (x_i >= x_detMin && x_i <= x_detMax))) {
                    t_best = 0;
                    x_best = x_i;
                    y_best = y_i;
                }
            }
        }
        return x_best;
    }
    
    /** \brief Finds y-coordinate of detector hit
        \param traj trajectory
        \param d_orient detector orientation
        \param x_det detector line x-position
        \param y_det detector line y-position
        \param y_detMin detector y min
        \param y_detMax detector y max
        \param x_detMin detector x min
        \param x_detMax detector x max
        \return Finds y-coordinate of detector hit
    */
    public static double func_y_hit(List<List<double>> traj, int d_orient, double x_det, double y_det, double y_detMin, double y_detMax, double x_detMin, double x_detMax) {
        int num_pts = traj.Count;
        double t_best = -1;
        double x_best = 0;
        double y_best = 0;
        for (int i = 0; i < num_pts; i += 1) {
            double x_i = traj[i][0];
            double y_i = traj[i][1];
            if (d_orient == 0) {
                if (t_best < 0 && (x_i >= x_det && (y_i >= y_detMin && y_i <= y_detMax))) {
                    t_best = 0;
                    x_best = x_i;
                    y_best = y_i;
                }
            }
            else {
                if (t_best < 0 && (y_i >= y_det && (x_i >= x_detMin && x_i <= x_detMax))) {
                    t_best = 0;
                    x_best = x_i;
                    y_best = y_i;
                }
            }
        }
        return y_best;
    }
}
