/** \file InputParameters.cs
    \author Zhuo Zhang
    \brief Provides the function for reading inputs, the function for calculating derived values, and the function for checking the physical constraints and software constraints on the input
    \note Generated by Drasil v0.1-alpha
*/

using System;
using System.IO;

public class InputParameters {
    
    /** \brief Reads input from a file with the given file name
        \param filename name of the input file
        \param m particle mass (kg)
        \param q particle charge (C)
        \param x_0 initial x-position (m)
        \param y_0 initial y-position (m)
        \param v_x0 initial x-velocity (m/s)
        \param v_y0 initial y-velocity (m/s)
        \param E_x x-component of the electric field (N/C)
        \param E_y y-component of the electric field (N/C)
        \param B out-of-plane magnetic flux density (T)
        \param t_final final simulation time (s)
    */
    public static void get_input(string filename, out double m, out double q, out double x_0, out double y_0, out double v_x0, out double v_y0, out double E_x, out double E_y, out double B, out double t_final) {
        StreamReader infile;
        infile = new StreamReader(filename);
        infile.ReadLine();
        m = Double.Parse(infile.ReadLine());
        infile.ReadLine();
        q = Double.Parse(infile.ReadLine());
        infile.ReadLine();
        x_0 = Double.Parse(infile.ReadLine());
        infile.ReadLine();
        y_0 = Double.Parse(infile.ReadLine());
        infile.ReadLine();
        v_x0 = Double.Parse(infile.ReadLine());
        infile.ReadLine();
        v_y0 = Double.Parse(infile.ReadLine());
        infile.ReadLine();
        E_x = Double.Parse(infile.ReadLine());
        infile.ReadLine();
        E_y = Double.Parse(infile.ReadLine());
        infile.ReadLine();
        B = Double.Parse(infile.ReadLine());
        infile.ReadLine();
        t_final = Double.Parse(infile.ReadLine());
        infile.Close();
    }
    
    /** \brief Calculates values that can be immediately derived from the inputs
        \param q particle charge (C)
        \param m particle mass (kg)
        \param x_0 initial x-position (m)
        \param y_0 initial y-position (m)
        \param v_x0 initial x-velocity (m/s)
        \param v_y0 initial y-velocity (m/s)
        \param E_x x-component of the electric field (N/C)
        \param E_y y-component of the electric field (N/C)
        \param B out-of-plane magnetic flux density (T)
        \param κ charge-to-mass ratio (C/kg)
        \param s_0 initial state vector
        \param E_vect electric field vector (N/C)
        \param B_vect magnetic flux density vector (T)
    */
    public static void derived_values(double q, double m, double x_0, double y_0, double v_x0, double v_y0, double E_x, double E_y, double B, out double κ, out double s_0, out double E_vect, out double B_vect) {
        κ = q / m;
        
        s_0 = new double[] {x_0, y_0, v_x0, v_y0};
        
        E_vect = new double[] {E_x, E_y, 0.0};
        
        B_vect = new double[] {0.0, 0.0, B};
    }
    
    /** \brief Verifies that input values satisfy the physical constraints and software constraints
        \param m particle mass (kg)
        \param q particle charge (C)
        \param x_0 initial x-position (m)
        \param y_0 initial y-position (m)
        \param v_x0 initial x-velocity (m/s)
        \param v_y0 initial y-velocity (m/s)
        \param E_x x-component of the electric field (N/C)
        \param E_y y-component of the electric field (N/C)
        \param B out-of-plane magnetic flux density (T)
        \param t_final final simulation time (s)
    */
    public static void input_constraints(double m, double q, double x_0, double y_0, double v_x0, double v_y0, double E_x, double E_y, double B, double t_final) {
        if (!(Constants.m_min <= m && m <= Constants.m_max)) {
            Console.Write("Warning: ");
            Console.Write("m has value ");
            Console.Write(m);
            Console.Write(", but is suggested to be ");
            Console.Write("between ");
            Console.Write(Constants.m_min);
            Console.Write(" (m_min)");
            Console.Write(" and ");
            Console.Write(Constants.m_max);
            Console.Write(" (m_max)");
            Console.WriteLine(".");
        }
        if (!(-Constants.q_max <= q && q <= Constants.q_max)) {
            Console.Write("Warning: ");
            Console.Write("q has value ");
            Console.Write(q);
            Console.Write(", but is suggested to be ");
            Console.Write("between ");
            Console.Write(-Constants.q_max);
            Console.Write(" (-q_max)");
            Console.Write(" and ");
            Console.Write(Constants.q_max);
            Console.Write(" (q_max)");
            Console.WriteLine(".");
        }
        if (!(-Constants.v_max <= v_x0 && v_x0 <= Constants.v_max)) {
            Console.Write("Warning: ");
            Console.Write("v_x0 has value ");
            Console.Write(v_x0);
            Console.Write(", but is suggested to be ");
            Console.Write("between ");
            Console.Write(-Constants.v_max);
            Console.Write(" (-v_max)");
            Console.Write(" and ");
            Console.Write(Constants.v_max);
            Console.Write(" (v_max)");
            Console.WriteLine(".");
        }
        if (!(-Constants.v_max <= v_y0 && v_y0 <= Constants.v_max)) {
            Console.Write("Warning: ");
            Console.Write("v_y0 has value ");
            Console.Write(v_y0);
            Console.Write(", but is suggested to be ");
            Console.Write("between ");
            Console.Write(-Constants.v_max);
            Console.Write(" (-v_max)");
            Console.Write(" and ");
            Console.Write(Constants.v_max);
            Console.Write(" (v_max)");
            Console.WriteLine(".");
        }
        if (!(-Constants.E_max <= E_x && E_x <= Constants.E_max)) {
            Console.Write("Warning: ");
            Console.Write("E_x has value ");
            Console.Write(E_x);
            Console.Write(", but is suggested to be ");
            Console.Write("between ");
            Console.Write(-Constants.E_max);
            Console.Write(" (-E_max)");
            Console.Write(" and ");
            Console.Write(Constants.E_max);
            Console.Write(" (E_max)");
            Console.WriteLine(".");
        }
        if (!(-Constants.E_max <= E_y && E_y <= Constants.E_max)) {
            Console.Write("Warning: ");
            Console.Write("E_y has value ");
            Console.Write(E_y);
            Console.Write(", but is suggested to be ");
            Console.Write("between ");
            Console.Write(-Constants.E_max);
            Console.Write(" (-E_max)");
            Console.Write(" and ");
            Console.Write(Constants.E_max);
            Console.Write(" (E_max)");
            Console.WriteLine(".");
        }
        if (!(-Constants.B_max <= B && B <= Constants.B_max)) {
            Console.Write("Warning: ");
            Console.Write("B has value ");
            Console.Write(B);
            Console.Write(", but is suggested to be ");
            Console.Write("between ");
            Console.Write(-Constants.B_max);
            Console.Write(" (-B_max)");
            Console.Write(" and ");
            Console.Write(Constants.B_max);
            Console.Write(" (B_max)");
            Console.WriteLine(".");
        }
        if (!(t_final <= Constants.t_max)) {
            Console.Write("Warning: ");
            Console.Write("t_final has value ");
            Console.Write(t_final);
            Console.Write(", but is suggested to be ");
            Console.Write("below ");
            Console.Write(Constants.t_max);
            Console.Write(" (t_max)");
            Console.WriteLine(".");
        }
        
        if (!(m > 0.0)) {
            Console.Write("Warning: ");
            Console.Write("m has value ");
            Console.Write(m);
            Console.Write(", but is suggested to be ");
            Console.Write("above ");
            Console.Write(0.0);
            Console.WriteLine(".");
        }
        if (!(t_final > 0.0)) {
            Console.Write("Warning: ");
            Console.Write("t_final has value ");
            Console.Write(t_final);
            Console.Write(", but is suggested to be ");
            Console.Write("above ");
            Console.Write(0.0);
            Console.WriteLine(".");
        }
    }
}
