/** \file OutputFormat.cs
    \author Zhuo Zhang
    \brief Provides the function for writing outputs
    \note Generated by Drasil v0.1-alpha
*/

using System;
using System.Collections.Generic;
using System.IO;

public class OutputFormat {
    
    /** \brief Writes the output values to output.txt
        \param s dependent variables (m)
    */
    public static void write_output(List<double> s) {
        StreamWriter outputfile;
        outputfile = new StreamWriter("output.txt", false);
        outputfile.Write("s = ");
        outputfile.Write("[");
        for (int list_i1 = 0; list_i1 < s.Count - 1; list_i1++) {
            outputfile.Write(s[list_i1]);
            outputfile.Write(", ");
        }
        if (s.Count > 0) {
            outputfile.Write(s[s.Count - 1]);
        }
        outputfile.WriteLine("]");
        outputfile.Close();
    }
}
