/** \file OutputFormat.cs
    \author Zhuo Zhang
    \brief Provides the function for writing outputs
    \note Generated by Drasil v0.1-alpha
*/

using System;
using System.Collections.Generic;
using System.IO;

public class OutputFormat {
    
    /** \brief Writes the output values to output.txt
        \param s dependent variables (m)
        \param t_hit time of detector hit (s)
        \param x_hit x-coordinate of impact point (m)
        \param y_hit y-coordinate of impact point (m)
    */
    public static void write_output(List<double> s, double t_hit, double x_hit, double y_hit) {
        StreamWriter outputfile;
        outputfile = new StreamWriter("output.txt", false);
        outputfile.Write("s = ");
        outputfile.Write("[");
        for (int list_i1 = 0; list_i1 < s.Count - 1; list_i1++) {
            outputfile.Write(s[list_i1]);
            outputfile.Write(", ");
        }
        if (s.Count > 0) {
            outputfile.Write(s[s.Count - 1]);
        }
        outputfile.WriteLine("]");
        outputfile.Write("t_hit = ");
        outputfile.WriteLine(t_hit);
        outputfile.Write("x_hit = ");
        outputfile.WriteLine(x_hit);
        outputfile.Write("y_hit = ");
        outputfile.WriteLine(y_hit);
        outputfile.Close();
    }
}
